adobecom/dc

blocks/list.js
blocks/widget/widget.css
blocks/widget/widget.js
blocks/widget/widget.md

Resolves : [MWPW-116636](https://jira.corp.adobe.com/browse/MWPW-116636)

MWPW-116636

---

styles/styles.css

- https://footer-changes--acrobat--adobecom.hlx.page/jpg-to-pdf

Verb sub footer styling

---

styles/styles.css

- https://main--acrobat--adobecom.hlx.page/

how-to styles

---

styles/styles.css

https://browser-extension-modal-styles--acrobat--adobecom.hlx.page/

styles for browser extension modal

---

blocks/eventwrapper/eventwrapper.css
blocks/widget/widget.css

- https://placeholdertest--acrobat--adobecom.hlx.page/
- https://placeholdertest--acrobat--adobecom.hlx.page/acrobat/online/jpg-to-pdftest

test for placeholders

---

blocks/eventwrapper/eventwrapper.css
blocks/eventwrapper/eventwrapper.js
blocks/eventwrapper/eventwrapper.md
blocks/personalization/personalization.js
blocks/personalization/personalization.md

MWPW-120018

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js

Resolves : [MWPW-122635](https://jira.corp.adobe.com/browse/MWPW-122635)
Old - https://main--acrobat--adobecom.hlx.page/acrobat/online/pdf-to-excel
New - https://mwpw-122635--acrobat--adobecom.hlx.page/acrobat/online/pdf-to-excel

MWPW-122635

---

acrobat/scripts/dcLana.js
acrobat/scripts/scripts.js

Before: https://main--acrobat--adobecom.hlx.page/acrobat/online/pdf-to-excel?verb=dfd
After: https://mwpw-120316lana--acrobat--adobecom.hlx.page/acrobat/online/pdf-to-excel?verb=dfd

MWPW-120316 | Adding Lana logging to frictionless milo acrobat project

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js
acrobat/blocks/eventwrapper/eventwrapper.js
acrobat/blocks/personalization/personalization.css
acrobat/blocks/personalization/personalization.js

https://lcp_help--acrobat--adobecom.hlx.page/acrobat/online/pdf-to-ppt

LCP Updates

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js
acrobat/scripts/analytics/review.js
acrobat/scripts/analytics/reviewFeedback.js
acrobat/scripts/frictionless.js
acrobat/scripts/scripts.js
acrobat/styles/styles.css

[MWPW-123752](https://jira.corp.adobe.com/browse/MWPW-123752)

MWPW-123752

---

acrobat/styles/styles.css

Before: https://main--dc--adobecom.hlx.page/fragments/personalization-summary-frags/pdf-to-ppt/summary-frag-how-to
After: https://mwpw-124252--dc--adobecom.hlx.page/fragments/personalization-summary-frags/pdf-to-ppt/summary-frag-how-to

MWPW-124252 | Fixing Spacing issues with bold text in How to block

---

acrobat/scripts/scripts.js
acrobat/styles/styles.css

Resolves [MWPW-124169](https://jira.corp.adobe.com/browse/MWPW-124169)

MWPW-124169

---

acrobat/styles/styles.css

Main URL: https://main--dc--adobecom.hlx.page/dc-shared/fragments/frictionless-personalization-xfs/crop-pdf-xfs/how-to/default
New URL: https://mwpw-124169-1--dc--adobecom.hlx.page/dc-shared/fragments/frictionless-personalization-xfs/crop-pdf-xfs/how-to/default

MWPW-124169 | Fix for removing max-width setting of 700px

---

acrobat/styles/styles.css

Revert "MWPW-124169 | Fix for removing max-width setting of 700px"

---

acrobat/styles/styles.css

Revert "Revert "MWPW-124169 | Fix for removing max-width setting of 700px""

---

acrobat/blocks/eventwrapper/eventwrapper.js
acrobat/scripts/frictionless.js

Resolves : [MWPW-125163](https://jira.corp.adobe.com/browse/MWPW-125163)
Resolves : [MWPW-125163](https://jira.corp.adobe.com/browse/MWPW-125163)

MWPW-125163

---

acrobat/blocks/eventwrapper/eventwrapper.css
acrobat/blocks/eventwrapper/eventwrapper.js

Resolves : [MWPW-125383](https://jira.corp.adobe.com/browse/MWPW-125383)

MWPW-125383

---

acrobat/scripts/scripts.js

Added the new regions listed in [MWPW-124903](https://jira.corp.adobe.com/browse/MWPW-124903) as locales to the config object.

MWPW-124903 Add new regions

---

acrobat/blocks/eventwrapper/eventwrapper.js

Resolves : [MWPW-125607](https://jira.corp.adobe.com/browse/MWPW-125607)

MWPW-125607

---

acrobat/styles/styles.css

Before: https://main--dc--adobecom.hlx.page/acrobat/online/crop-pdf
After: https://mwpw-125711--dc--adobecom.hlx.page/acrobat/online/crop-pdf

MWPW-125711 | Fixing the indentation of question and answer in accordion

---

acrobat/scripts/scripts.js

Before: https://main--dc--adobecom.hlx.page/acrobat/online/crop-pdf
After: https://mwpw-124901--dc--adobecom.hlx.page/acrobat/online/crop-pdf

MWPW-124901 | Adding proddomain config for link transformation

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js
acrobat/blocks/eventwrapper/eventwrapper.js
acrobat/scripts/alloy/browserExt.js
acrobat/scripts/alloy/dc-converter-widget.js
acrobat/scripts/alloy/review.js
acrobat/scripts/alloy/reviewFeedback.js
acrobat/scripts/contentSecurityPolicy/csp.js
acrobat/scripts/contentSecurityPolicy/dev.js
acrobat/scripts/contentSecurityPolicy/prod.js
acrobat/scripts/contentSecurityPolicy/stage.js
acrobat/scripts/dcLana.js
acrobat/scripts/frictionless.js
acrobat/scripts/scripts.js

Resolves : [MWPW-125810](https://jira.corp.adobe.com/browse/MWPW-125810)

MWPW-125810

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js

Resolves : [MWPW-126070](https://jira.corp.adobe.com/browse/MWPW-126070)

MWPW-126070

---

acrobat/styles/styles.css

Resolves https://jira.corp.adobe.com/browse/MWPW-125749 
Before: https://main--dc--adobecom.hlx.page/drafts/sonja/test
After: https://mwpw-125749-review-desing-details--dc--adobecom.hlx.page/drafts/sonja/test

Mwpw 125749 review desing details

---

acrobat/scripts/alloy/reviewFeedback.js
acrobat/scripts/frictionless.js

Resolves [MWPW-125756](https://jira.corp.adobe.com/browse/MWPW-125756)

MWPW-125756

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js
acrobat/blocks/dc-converter-widget/dc-converter-widget.md

GO TO urls and dc generate cache urls can be set by authoring, and if they are not set, they will be dynamically generated. 
Before: https://main--dc--adobecom.hlx.page/drafts/sonja/converter
After: 
https://mwpw-125812--dc--adobecom.hlx.page/drafts/sonja/converter

Mwpw 125812

---

acrobat/styles/styles.css

Resolves : [MWPW-124595](https://jira.corp.adobe.com/browse/MWPW-124595)

MWPW-124595

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js

Weekly widget release 2.39.1_1.170.2 

---

tools/importScript/createSection.js
tools/importScript/import-frictionless.js
tools/importScript/import.js
tools/importScript/rules/accordion.js
tools/importScript/rules/breadcrumbs.js
tools/importScript/rules/columns.js
tools/importScript/rules/dcConverterWidget.js
tools/importScript/rules/eventWrapper.js
tools/importScript/rules/footer.js
tools/importScript/rules/iconblock.js
tools/importScript/rules/image.js
tools/importScript/rules/jumpSection.js
tools/importScript/rules/marquee.js
tools/importScript/rules/metaData.js
tools/importScript/rules/review.js
tools/importScript/rules/tabs.js
tools/importScript/rules/text.js
tools/importScript/rules/verbFooter.js
tools/importScript/utils/getStyles.js

https://jira.corp.adobe.com/browse/MWPW-125813
Helix import ui: https://github.com/adobe/helix-importer-ui
Demo: https://adobe-my.sharepoint.com/personal/ronsain_adobe_com/_layouts/15/stream.aspx?id=%2Fpersonal%2Fronsain%5Fadobe%5Fcom%2FDocuments%2FRecordings%2FMILO%20Importer%20Tool%20Demo%20%5F%20DC%2D20230309%5F170314%2DMeeting%20Recording%2Emp4&ga=1

MWPW-125813: Added scripts for importer tool

---

acrobat/blocks/personalization/personalization.js

Resolves : [MWPW-127199](https://jira.corp.adobe.com/browse/MWPW-127199)
https://mwpw-127199--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt

MWPW-127199

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js

Old: https://mwpw-127442--dc--adobecom.hlx.page/de/acrobat/online/pdf-to-ppt
Existing:  https://stage--dc--adobecom.hlx.page/de/acrobat/online/pdf-to-ppt

MWPW-127442 | Reading locale from path compared to DOM value

---

acrobat/blocks/list.js
acrobat/blocks/promotion/promotion.js
acrobat/scripts/scripts.js

Resolves :[MWPW-127980](https://jira.corp.adobe.com/browse/MWPW-127980)

MWPW-127980

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js

weekly widget update for dev/stage: 2.39.1_1.171.1

---

acrobat/blocks/eventwrapper/eventwrapper.css

Resolves: https://jira.corp.adobe.com/browse/MWPW-127128
Before: https://stage--dc--adobecom.hlx.page/acrobat/online/pdf-to-word
After: https://mwpw-127128-star-rating-section-overlap--dc--adobecom.hlx.page/acrobat/online/pdf-to-word

MWPW-127128: Fixed rating section overlap

---

acrobat/scripts/utils.js

Resolve: https://jira.corp.adobe.com/browse/MWPW-128105
This should be tested on published stage once this PR is merged.

MWPW-128105 - milo libs param on stage.adobe.com

---

acrobat/styles/styles.css

Resolves: https://jira.corp.adobe.com/browse/MWPW-124601
Before: https://main--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt
After: https://mwpw-124601-verb-subfooter-alignment--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt

MWPW-124601 - verb footer online tools aligned with column titles

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js
acrobat/scripts/contentSecurityPolicy/dev.js
acrobat/scripts/contentSecurityPolicy/prod.js
acrobat/scripts/contentSecurityPolicy/stage.js

Resolves a portion of [MWPW-127299](https://jira.corp.adobe.com/browse/MWPW-127299)

MWPW-127299

---

acrobat/styles/styles.css

Resolves: https://jira.corp.adobe.com/browse/MWPW-124598
After: https://mwpw-124598-space-between-bullet-points--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt

MWPW-124598: Added margin to widget bullet list

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js

Resolves :  [MWPW-129013](https://jira.corp.adobe.com/browse/MWPW-129013)
https://mwpw-129013--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt
https://main--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt

MWPW-129013

---

acrobat/scripts/alloy/browserExt.js
acrobat/scripts/frictionless.js

Resolves: https://jira.corp.adobe.com/browse/MWPW-128891
After: https://mwpw-128891-clicks-not-being-captured--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt

MWPW-128891: Added new event for analytics

---

acrobat/scripts/dcLana.js
acrobat/scripts/scripts.js

Resolves : [MWPW-129213](https://jira.corp.adobe.com/browse/MWPW-129213)

MWPW-129213

---

acrobat/scripts/frictionless.js

Resolves: https://jira.corp.adobe.com/browse/MWPW-128882
After: https://mwpw-128882-user-ratings-not-being-reported--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt

MWPW-128882: Added eventlisteners to review

---

acrobat/scripts/scripts.js

Resolves : [MWPW-129220](https://jira.corp.adobe.com/browse/MWPW-129220)

MWPW-129220

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js
acrobat/scripts/dcLana.js
acrobat/scripts/scripts.js
test/scripts/dcLana.test.js

Resolves : [MWPW-129368](https://jira.corp.adobe.com/browse/MWPW-129368
)
Improvements to DC Widget for LCP gains 
Minor refactor and test update

MWPW-129368

---

acrobat/blocks/eventwrapper/eventwrapper.js

Resolves : [MWPW-129282](https://jira.corp.adobe.com/browse/MWPW-129282)

MWPW-129282

---

acrobat/scripts/scripts.js

Resolves : [MWPW-129451](https://jira.corp.adobe.com/browse/MWPW-129451)

MWPW-129451 try loading widget, csp, and utils in parallel

---

acrobat/styles/styles.css

Resolves: https://jira.corp.adobe.com/browse/MWPW-129156
Before: https://www.adobe.com/acrobat/online/pdf-to-ppt
After: https://mwpw-129156--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt

MWPW-129156 Fix verb footer style

---

.github/workflows/run-inside.yml
.github/workflows/run-tests.yml

Need to run the unit and inside tests on the main branch

MWPW-129472 Add the main branch to workflows

---

acrobat/scripts/contentSecurityPolicy/stage.js

updating sitemap locations 

---

acrobat/scripts/alloy/browserExt.js
acrobat/scripts/frictionless.js

@Blainegunn @seanchoi-dev @SonjaPopovic , please let me know if this is acceptable, or should I add separate file with separate event. Thank you.
Resolves: https://jira.corp.adobe.com/browse/MWPW-128891
After: https://mwpw-128891-clicks-not-being-captured--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt

MWPW-128891: Added impression interaction event

---

acrobat/scripts/contentSecurityPolicy/csp.js
acrobat/scripts/contentSecurityPolicy/dev.js
acrobat/scripts/contentSecurityPolicy/prod.js
acrobat/scripts/contentSecurityPolicy/stage.js

Resolves : [MWPW-129578](https://jira.corp.adobe.com/browse/MWPW-129578)

MWPW-129578

---

helix-query.yaml
helix-sitemap.yaml

Related to https://jira.corp.adobe.com/browse/MWPW-109332
Adds hk, th, tw sitemaps

Sitemap expansion

---

helix-sitemap.yaml

Addresses: https://jira.corp.adobe.com/browse/MWPW-129768
- https://hparra-patch-1--dc--adobecom.hlx.page

Add x-default to helix-sitemap.yaml

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js
acrobat/scripts/scripts.js

Resolve: [MWPW-130146](https://jira.corp.adobe.com/browse/MWPW-130146)
Before: https://main--dc--adobecom.hlx.live/acrobat/online/jpg-to-pdf
After: https://live-widget-stage--dc--adobecom.hlx.live/acrobat/online/jpg-to-pdf

Live widget to point stage

---

acrobat/styles/cls.css
acrobat/styles/styles.css

Resolves : [MWPW-129829](https://jira.corp.adobe.com/browse/MWPW-129829)

MWPW-129829

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js

Resolves : [DCXY-16859](https://jira.corp.adobe.com/browse/DCXY-16859) & [DCXY-16860]( https://jira.corp.adobe.com/browse/DCXY-16860)

DCXY-16859 DCXY-16860 pass es-MX locale to widget for SEO optimization

---

acrobat/scripts/scripts.js

Resolves: [MWPW-129959](https://jira.corp.adobe.com/browse/MWPW-129959) 🤞

MWPW-129959

---

acrobat/scripts/scripts.js

https://jira.corp.adobe.com/browse/DOTCOM-90393

DOTCOM-90393

---

acrobat/blocks/eventwrapper/eventwrapper.css

Resolves: https://jira.corp.adobe.com/browse/MWPW-131160
Before: https://stage--dc--adobecom.hlx.page/acrobat/online/convert-pdf
After: https://puru-MWPW-131160--dc--puruadobe.hlx.page/acrobat/online/convert-pdf

MWPW-131160

---

acrobat/styles/styles.css

Resolves: https://jira.corp.adobe.com/browse/MWPW-131400 
Before: https://www.stage.adobe.com/acrobat/online/merge-pdf.html 
After: https://mwpw-131400--dc--puruadobe.hlx.page/acrobat/online/merge-pdf

MWPW-131400 Fix converter overlap issue

---

acrobat/blocks/eventwrapper/eventwrapper.js

Revert "MWPW-129281"

---

acrobat/scripts/contentSecurityPolicy/dev.js
acrobat/scripts/scripts.js

Resolves: https://jira.corp.adobe.com/browse/MWPW-131256
Before: https://stage--dc--adobecom.hlx.live/acrobat/online/pdf-to-ppt
After: https://mwpw-131256-milo-libs--dc--adobecom.hlx.live/acrobat/online/pdf-to-ppt

MWPW-131256: Fetching milo libs from .live for live pages

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js

Resolves former MWPW [DCXY-17389](https://jira.corp.adobe.com/browse/DCXY-17389)
Prevent the case where the widget gets to the hydration step before the pre-rendered dropzone is inserted in the DOM.

DCXY-17389 Synchronize hydration with creation of dropzone

---

acrobat/scripts/contentSecurityPolicy/dev.js
acrobat/scripts/contentSecurityPolicy/stage.js

Resolves: [MWPW-131256](https://jira.corp.adobe.com/browse/MWPW-131256)
Before: https://stage--dc--adobecom.hlx.live/acrobat/online/pdf-to-ppt?milolibs=uar-integration
After: https://mwpw-131256-milo-libs--dc--adobecom.hlx.live/acrobat/online/pdf-to-ppt?milolibs=uar-integration

MWPW-131256: Update dev and stage csp

---

acrobat/blocks/personalization/personalization.css
acrobat/styles/styles.css

Please note that the widget version is different on stage branch compared to dev branches.
Resolves: [132502](https://jira.corp.adobe.com/browse/MWPW-132502)
Before: https://stage--dc--adobecom.hlx.page/acrobat/online/pdf-to-jpg
After: https://mwpw-132502-widget-dropdonw-menu--dc--adobecom.hlx.page/acrobat/online/pdf-to-jpg

mwpw-132502: Added isolation property to main

---

acrobat/blocks/eventwrapper/eventwrapper.js

Resolves: [MWPW-132652](https://jira.corp.adobe.com/browse/MWPW-132652)
After: https://mwpw-132652-extension-popup-parameters--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt

MWPW-132652:Added browser extension modal analytics events

---

acrobat/scripts/scripts.js
test/scripts/scripts.jest.js

Resolves: [MWPW-132720](https://jira.corp.adobe.com/browse/MWPW-132720)
Before: https://stage--dc--adobecom.hlx.page/acrobat/
After: https://mwpw-132720-remove-loaddelayed--dc--adobecom.hlx.page/acrobat/

MWPW-132720: Removed loadDelayed method

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js
acrobat/styles/styles.css

Resolves : [MWPW-133310](https://jira.corp.adobe.com/browse/MWPW-133310)

MWPW-133310

---

acrobat/scripts/scripts.js

Revert "Update itef for /la geo"

---

acrobat/styles/styles.css

Resolves: [MWPW-133348](https://jira.corp.adobe.com/browse/MWPW-133348)
Before: https://stage--dc--adobecom.hlx.page/fr/acrobat/online/convert-pdf
After: https://mwpw-133348-browser-extension-modal-padding--dc--adobecom.hlx.page/fr/acrobat/online/convert-pdf

MWPW-133348: Fixed extension modal padding

---

.gitignore
package.json
tools/cspUpdate/README.md
tools/cspUpdate/cspUpdate.js

Resolves: [MWPW-122816](https://jira.corp.adobe.com/browse/MWPW-122816)
To test locally:
-  Download attached csv file
- Create test branch on GitHub webapp
- Change BRANCH variable value to newly created branch name 
- Follow the instructions in README
[lana-dc-csp-2023-07-13.csv](https://github.com/adobecom/dc/files/12040307/lana-dc-csp-2023-07-13.csv)

MWPW-122816: Added script for automating csp update process

---

acrobat/scripts/scripts.js

Resolves : [MWPW-133942](https://jira.corp.adobe.com/browse/MWPW-133942)

MWPW-133942

---

acrobat/styles/styles.css

Resolves: https://jira.corp.adobe.com/browse/MWPW-133691
**URL-s**
After: https://mwpw-133691-browser-extension-popup-right--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt

MWPW-133691 - browser extension popup to bottom right

---

acrobat/scripts/contentSecurityPolicy/csp.js
acrobat/scripts/contentSecurityPolicy/dev.js
acrobat/scripts/contentSecurityPolicy/prod.js
acrobat/scripts/contentSecurityPolicy/stage.js

To support Level-2 Fill & Sign verb

DCXY-18423 add child-src rule, with blob: for dev and stage

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js
acrobat/styles/styles.css

Resolves : [MWPW-13163](https://jira.corp.adobe.com/browse/MWPW-131632)

MWPW-131632

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js
acrobat/styles/styles.css

Revert "MWPW-131632"

---

acrobat/blocks/dc-converter-widget-ootb/dc-converter-widget-ootb.js
acrobat/scripts/scripts.js
acrobat/styles/styles.css

Resolves : [MWPW-134069](https://jira.corp.adobe.com/browse/MWPW-134069)

MWPW-134069 - OOTB Widget

---

test/blocks/dc-converter-widget-ootb/dc-converter-widget-ootb.jest.js
test/blocks/dc-converter-widget-ootb/dc-converter-widget-ootb.test.js
test/blocks/dc-converter-widget-ootb/mocks/body.html
test/blocks/dc-converter-widget-ootb/mocks/body_cache.html
test/blocks/dc-converter-widget-ootb/mocks/head.html
test/blocks/dc-converter-widget-ootb/mocks/widget.html
test/blocks/eventwrapper/eventwrapper.test.js
test/blocks/pricing-card/mocks/body_noinitialoption.html
test/blocks/pricing-card/pricing-card.test.js

- Added unit tests for dc-converter-widget-ootb
- Improved code coverage for eventwrapper and pricing-card

MWPW-134816 Improve Unit Test Coverage

---

acrobat/blocks/dc-converter-widget-ootb/dc-converter-widget-ootb.js
acrobat/blocks/dc-converter-widget/dc-converter-widget.js
acrobat/scripts/scripts.js

**Resolves:** https://jira.corp.adobe.com/browse/MWPW-134352
**None:**
This PR is additional config for il/he locale
**Links:**
Before: https://stage--dc--adobecom.hlx.page/il_he/acrobat/online/draft/dragana-test-page
After: https://mwpw-134352-linking-confing-for-il-he--dc--adobecom.hlx.page/il_he/acrobat/online/draft/dragana-test-page

MWPW-134352 - linking confing for il/he

---

acrobat/styles/styles.css

Resolves : [DCXY-18730](https://jira.corp.adobe.com/browse/DCXY-18730) / Clone [MWPW-135079](https://jira.corp.adobe.com/browse/MWPW-135079)

DCXY-18730 use min-height for fsw

---

acrobat/scripts/contentSecurityPolicy/prod.js
acrobat/scripts/contentSecurityPolicy/stage.js

Resolves : [MWPW-135188](https://jira.corp.adobe.com/browse/MWPW-135188)

MWPW-135188 JP CSP Update

---

acrobat/scripts/dcLana.js

Minor fix to help unit test pass

fixing unit test

---

acrobat/scripts/contentSecurityPolicy/dev.js
acrobat/scripts/contentSecurityPolicy/prod.js
acrobat/scripts/contentSecurityPolicy/stage.js

requested by the DC Web team @ladutko and @gyeung

DCXY-18948 add UCv3 commerce frame-src hosts for free trial

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js

Resolves : [MWPW-135361](https://jira.corp.adobe.com/browse/MWPW-135361)

MWPW-135361 Gen Cache Update

---

acrobat/blocks/eventwrapper/eventwrapper.js

Minor bug fix.
Resolves: [MWPW-133658](https://jira.corp.adobe.com/browse/MWPW-133658)
Before: https://stage--dc--adobecom.hlx.live/acrobat/online/sign-pdf?app!versions=latest
After: https://mwpw-133658-l1-l2-fillsign--dc--adobecom.hlx.live/acrobat/online/sign-pdf?app!versions=latest

MWPW-133658: Bug fix

---

acrobat/blocks/eventwrapper/eventwrapper.css

Resolves: [MWPW-133658](https://jira.corp.adobe.com/browse/MWPW-133658)
Before: https://stage--dc--adobecom.hlx.live/acrobat/online/sign-pdf?app!versions=latest
After: https://mwpw-133658-l1-l2-fillsign--dc--adobecom.hlx.live/acrobat/online/sign-pdf?app!versions=latest

MWPW-133658: Changed widget height

---

acrobat/blocks/eventwrapper/eventwrapper.css

Resolves: [MWPW-133658](https://jira.corp.adobe.com/browse/MWPW-133658)
Before: https://stage--dc--adobecom.hlx.live/acrobat/online/sign-pdf?app!versions=latest
After: https://mwpw-133658-l1-l2-fillsign--dc--adobecom.hlx.live/acrobat/online/sign-pdf?app!versions=latest

Mwpw 133658 l1 l2 fillsign

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js
acrobat/scripts/scripts.js
test/scripts/scripts.jest.js

Resolves : [MWPW-135361](https://jira.corp.adobe.com/browse/MWPW-135361)

MWPW-135361

---

.github/workflows/test-milo.yml

Ticket: [MWPW-132707](https://jira.corp.adobe.com/browse/MWPW-132707)
Update Github Actions workflow for smoke tests to execute against Windows, Mac and Linux.
https://mwpw-132707-cross-platform_testing--dc--adobecom.hlx.live/acrobat/online/sign-pdf?martech=off

Run smoke tests on different platforms

---

acrobat/blocks/eventwrapper/eventwrapper.css
acrobat/blocks/eventwrapper/eventwrapper.js

Resolves: [MWPW-133659](https://jira.corp.adobe.com/browse/MWPW-133659)
Before: https://stage--dc--adobecom.hlx.live/acrobat/online/rotate-pdf
After: https://mwpw-133659-l1-to-l2-rotate-pdf--dc--adobecom.hlx.live/acrobat/online/rotate-pdf

Fixed style bug on rotate-pdf for mobile

---

acrobat/blocks/eventwrapper/eventwrapper.js

Resolves: https://jira.corp.adobe.com/browse/MWPW-133659
**LINKS:**
Before: https://stage--dc--adobecom.hlx.page/acrobat/online/rotate-pdf
After: https://mwpw-133659-l1-to-l2-rotate-pdf--dc--adobecom.hlx.page/acrobat/online/rotate-pdf

MWPW-133659 - rotate-page - hide the content after deleting selecting page

---

acrobat/scripts/scripts.js

Resolves : [MWPW-135835](https://jira.corp.adobe.com/browse/MWPW-135835)
Replaces #334 
Let's just remove the app-launcher prefetch entirely. It's causing problems for our QE testing on stage, since it's loading the prod version of the script which does not align with stage.

MWPW-135835 Remove app launcher prefetch

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js
acrobat/scripts/legacy.js
acrobat/scripts/scripts.js
head.html

Re-Resolves : [MWPW-127443](https://jira.corp.adobe.com/browse/MWPW-127443)
Sadly `userAgentData` doesn't work on some of the legacy browser we target
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgentData

MWPW-127443

---

acrobat/blocks/eventwrapper/eventwrapper.js

Mwpw 135029

---

.github/workflows/test-milo.yml
test/e2e/frictionless/features/smoke/analytics.feature
test/e2e/frictionless/features/smoke/converter.feature
test/e2e/frictionless/features/smoke/eventwrapper.feature
test/e2e/frictionless/features/smoke/gnav.feature
test/e2e/frictionless/features/smoke/review.feature
test/e2e/frictionless/page-objects/compresspdf.page.js
test/e2e/frictionless/page-objects/dcgnav.page.js
test/e2e/frictionless/page-objects/frictionless.page.js
test/e2e/frictionless/step-definitions/dc.steps.js
test/e2e/frictionless/support/cardinal.js

- Add a Gnav test
- Update test case tags
- Update the E2E workflow to use operators on tags

MWPW-123527  Gnav test

---

.github/workflows/run-lint.yml

Resolves: [MWPW-129470](https://jira.corp.adobe.com/browse/MWPW-129470)
Before: https://stage--dc--adobecom.hlx.live/acrobat/online/pdf-to-jpg
After: https://mwpw-129470-js-and-css-lint--dc--adobecom.hlx.live/acrobat/online/pdf-to-jpg

MWPW-129470: Added GitHub Action for js and css lint

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js
acrobat/styles/styles.css

Resolves : [MWPW-136010](https://jira.corp.adobe.com/browse/MWPW-136010)
Test, if approved will be implement in a more _elegant_ way

Mwpw 136010

---

.eslintrc.js

Update eslintrc to prevent VSCode lint-ing noise

MWPW-136159 Update eslintrc.js as per Milo

---

acrobat/styles/styles.css

Resolve: [MWPW-137009](https://jira.corp.adobe.com/browse/MWPW-137009)
Before: https://stage--dc--adobecom.hlx.live/acrobat/online/compress-pdf
After: https://mwpw-137009-review-block-title--dc--adobecom.hlx.live/acrobat/online/compress-pdf

MWPW-137009: Fixed widget overlapping review title bug

---

404.html

Resolves: https://jira.corp.adobe.com/browse/MWPW-136655
**Links:**
Before: https://main--dc--adobecom.hlx.live/drafts/dragana/test5
After: https://mwpw-136655-meta-tag-in-404--dc--adobecom.hlx.live/drafts/dragana/test5

MWPW-136655 - added meta tad in 404

---

acrobat/styles/styles.css

Resolves: [MWPW-137111](https://jira.corp.adobe.com/browse/MWPW-137111)
Before: https://stage--dc--adobecom.hlx.live/acrobat/online/rotate-pdf
After: https://mwpw-137111-region-selector-modal--dc--adobecom.hlx.live/acrobat/online/rotate-pdf

MWPW-137111: Fixed region selector modal animation bug

---

acrobat/styles/styles.css

Resolves : [MWPW-137135](https://jira.corp.adobe.com/browse/MWPW-137135)

MWPW-137135

---

404.html

Revert "MWPW-136655 - added meta tad in 404"

---

.gitignore
package-lock.json
package.json
test/e2e/frictionless/features/regression/analytics/analytics_spec.yml
test/e2e/frictionless/features/regression/resources_analytics.feature
test/e2e/frictionless/features/regression/resources_analytics/analytics_spec.yml
test/e2e/frictionless/step-definitions/dc.steps.js

- Analytics impression is controlled by the server side. Currently DC resources pages behave randomly in tracking impressions. Therefore, this test is not stable. 
- Merge the test first, and then will work with the analytics team to find a solution
To run the test case:
```
npx run test/e2e/frictionless -t @MWPW-137347 --enableAnalytics
```

MWPW-133317 Analytics test for resources pages

---

acrobat/scripts/scripts.js

Resolves: [MWPW-137308](https://jira.corp.adobe.com/browse/MWPW-137308)
Before: https://stage--dc--adobecom.hlx.live/acrobat/
After: https://mwpw-137308-scheduler-yield--dc--adobecom.hlx.live/acrobat/

Mwpw 137308 scheduler yield

---

acrobat/blocks/eventwrapper/eventwrapper.js

Resolves: [MWPW-137415](https://jira.corp.adobe.com/browse/MWPW-137415)
Before: https://stage--dc--adobecom.hlx.live/acrobat/online/pdf-to-ppt
After: https://mwpw-137415-browser-extension-analytics--dc--adobecom.hlx.live/acrobat/online/pdf-to-ppt

Mwpw 137415 browser extension analytics

---

test/e2e/frictionless/features/regression/eventwrapper.feature
test/e2e/frictionless/page-objects/frictionless.page.js
test/e2e/frictionless/page-objects/pdfwidget.section.js
test/e2e/frictionless/step-definitions/dc.steps.js

Resolves: https://jira.corp.adobe.com/browse/MWPW-137181
Ticket for rotate-pdf page: https://jira.corp.adobe.com/browse/MWPW-137378
Ticket for sign-pdf page: https://jira.corp.adobe.com/browse/MWPW-137439

MWPW-137181 -  sign and rotate eventwrapper test

---

head.html

Resolves :  [MWPW-137736](https://jira.corp.adobe.com/browse/MWPW-137736)

MWPW-137736

---

tools/loc/glaas.html
tools/loc/index.html
tools/loc/translation.css
tools/sidekick/config.json

- Adding html files for localization in dc
Currently, this change will be on `loc` branch
Resolves: [MWPW-137590](https://jira.corp.adobe.com/browse/MWPW-137590)

MWPW-137590: add loc html

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js

Resolves : [MWPW-137700](https://jira.corp.adobe.com/browse/MWPW-137700)

MWPW-137700

---

404.html

Revert "MWPW-136655-meta-tag-in-404-v2"

---

404.html

merge after today's delployment

Revert "Revert "MWPW-136655-meta-tag-in-404-v2""

---

.github/workflows/test-page-published.yml
package-lock.json
package.json

- Use the new Playwright docker image
- Update the Platform-UI library

Fix tests and workflow

---

acrobat/scripts/dcLana.js
acrobat/scripts/scripts.js

Resolves: [MWPW-138029](https://jira.corp.adobe.com/browse/MWPW-138029)
This PR will provide default tag for lana logs, in cases where tag is not explicitly defined. Also, existing tag names have been changed in order to be more true to its source.
Before: https://main--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt?lanadebug&martech=off
After: https://mwpw-138029-default-tag-lana-logs--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt?lanadebug&martech=off

Added default tag for lana logs, changed existing tags

---

acrobat/blocks/eventwrapper/eventwrapper.css

Resolves: [MWPW-137766](https://jira.corp.adobe.com/browse/MWPW-137766)
**LINKS:**
Before: https://www.stage.adobe.com/acrobat/online/rotate-pdf.html
After: https://mwpw-137766-rotate-pdf-progress-screen-height--dc--adobecom.hlx.live/acrobat/online/rotate-pdf

MWPW-137766  - rotate pdf progress screen widget height

---

acrobat/scripts/contentSecurityPolicy/dev.js
acrobat/scripts/contentSecurityPolicy/prod.js
acrobat/scripts/contentSecurityPolicy/stage.js

Resolves: https://jira.corp.adobe.com/browse/MWPW-138256
**Links:** 
Before: https://stage--dc--adobecom.hlx.live/acrobat/online/sign-pdf
After: https://mwpw-138256-chimera-api-csp--dc--adobecom.hlx.live/acrobat/online/sign-pdf

MWPW-138256 - chimera api csp

---

test/e2e/frictionless/features/regression/converter.feature
test/e2e/frictionless/features/regression/eventwrapper.feature
test/e2e/frictionless/page-objects/frictionless.page.js
test/e2e/frictionless/step-definitions/dc.steps.js

Resolves: https://jira.corp.adobe.com/browse/MWPW-137200
Test ticket for Converter: https://jira.corp.adobe.com/browse/MWPW-137197
Test ticket for Eventwrapper: https://jira.corp.adobe.com/browse/MWPW-138330

MWPW-137200 - Password protect pdf test

---

.github/workflows/metadata-published.yml

Fix the workflow that monitors metadata changes

Fix a workflow

---

test/e2e/frictionless/features/regression/caas.feature
test/e2e/frictionless/features/smoke/caas.feature
test/e2e/frictionless/page-objects/caas.section.js
test/e2e/frictionless/step-definitions/dc.steps.js

Resolves: [MWPW-138024](https://jira.corp.adobe.com/browse/MWPW-138024)

MWPW-138024: Smoke test for CaaS block

---

acrobat/img/favicons/favicon.webmanifest

Resolves: https://jira.corp.adobe.com/browse/MWPW-138428
**Links:**
Before: 
- https://stage--dc--adobecom.hlx.live/acrobat/online/rotate-pdf
- https://stage--dc--adobecom.hlx.live/acrobat/img/favicons/favicon.webmanifest
After:
- https://mwpw-138428-favicon-webmanifest-name--dc--adobecom.hlx.live/acrobat/online/rotate-pdf
- https://mwpw-138428-favicon-webmanifest-name--dc--adobecom.hlx.live/acrobat/img/favicons/favicon.webmanifest

MWPW-138428 - Webmanifest product name

---

README.md
package.json

- Update README
- helix-cli is renamed to aem-cli
- Update commands for unit tests
- Add a Codecov badget
- Update package.json
- Correct some fields

Update README and Package.json

---

test/e2e/features/smoke/commerce.feature
test/e2e/page-objects/commerce.section.js

Milo [PR1490](https://github.com/adobecom/milo/pull/1490) changed the selectors of price elements.

Test fix for Milo PR1490

---

acrobat/scripts/contentSecurityPolicy/dev.js
acrobat/scripts/contentSecurityPolicy/prod.js
acrobat/scripts/contentSecurityPolicy/stage.js

Reverts adobecom/dc#454
Launch script has been fixed.

Revert "MWPW-139087 Fix CSP"

---

acrobat/styles/styles.css

Resolves : [MWPW-139206](https://jira.corp.adobe.com/browse/MWPW-139206)
Before: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf
After: https://mwpw-139206--dc--adobecom.hlx.page/acrobat/online/compress-pdf

MWPW-139206

---

.github/workflows/test-ing.yml
test/e2e/features/smoke/converter.feature
test/e2e/page-objects/pdfwidget.section.js
test/e2e/profiles.yml
test/e2e/step-definitions/dc.steps.js

- A monitoring test for sign.ing and edit.ing sites
- The test is scheduled once every day
To run the test locally, use the following commands.
```
npx run test/e2e -t @ing -p editing
npx run test/e2e -t @ing -p signing
```

MWPW-138283 ing domain smoke test

---

acrobat/scripts/scripts.js

Resolves: [[MWPW-139835](https://jira.corp.adobe.com/browse/MWPW-139835)]

Updated libs for stage hostname

---

tools/sidekick/config.json

Vicky Morel needs Use offer tool for dc
https://workfront.slack.com/archives/C03B0BUA75E/p1701735683207409
Resolves: [MWPW-140244](https://jira.corp.adobe.com/browse/MWPW-140244)

Adding "Use offer" tool into DC's sidekick.

---

package.json
test/scripts/scripts.jest.js

Resolves: [MWPW-140039](https://jira.corp.adobe.com/browse/MWPW-140039)

Wrote unit tests for setLibs function

---

acrobat/blocks/personalization/personalization.css

Addressed the CLS (Cumulative Layout Shift) issue related to the widget moving from 70px to 30px briefly when a user tries to upload a file immediately after clicking the main CTA.
Reviews is not longer visible during file processing, preventing CLS spikes.
Throttle your Chrome to slow 3G or fast 3G.
Visit one of the "problem" pages, e.g., https://www.adobe.com/acrobat/online/compress-pdf.html.
Wait for the main CTA to become enabled (no longer grey).
Click on the CTA and try to upload a file.
Verify that the widget no longer moving, reviews disappears meanwhile file is processed and that there is no significant CLS spike.
Resolves: [MWPW-140549](https://jira.corp.adobe.com/browse/MWPW-140549)
PDF to Word    
Before: https://www.adobe.com/acrobat/online/pdf-to-word.html
After: …

 MWPW-140549:  CLS on drag and drop or quick file selection - lintFix

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js

Quick fix for India web vitals, but we need to go over this table to make sure our locales match what's in generate-cache

load en-us generate cache for India

---

acrobat/scripts/contentSecurityPolicy/dev.js
acrobat/scripts/contentSecurityPolicy/prod.js
acrobat/scripts/contentSecurityPolicy/stage.js
acrobat/scripts/scripts.js

Add pdf embed api support for DC pages to view the pdf on page
Resolves: [MWPW-141071](https://jira.corp.adobe.com/browse/MWPW-141071)
Test URLs:
Before: https://main--dc--adobecom.hlx.live/drafts/rivero/adobe-acrobat-microsoft-365-brief?martech=off
After: https://mwpw-141071--dc--adobecom.hlx.live?martech=off

MWPW-141071 - Update to support PDFs displayed in SDK viewer

---

acrobat/scripts/scripts.js

Resolves : https://jira.corp.adobe.com/browse/MWPW-142711

MWPW-142711

---

edgeworkers/Acrobat_DC_web_prod/bundle.json
edgeworkers/Acrobat_DC_web_prod/main.js
edgeworkers/Acrobat_DC_web_prod/utils/csp/index.js
edgeworkers/Acrobat_DC_web_prod/utils/locales.js
edgeworkers/Acrobat_DC_web_prod/utils/verbs.js
test/edgeworkers/Acrobat_DC_web_prod/main.jest.js

Updated with version 0.83 from stg
Related ticket: [MWPW-141047](https://jira.corp.adobe.com/browse/MWPW-141047)
https://mwpw-141047-update-ew--dc--adobecom.hlx.live/acrobat/online/jpg-to-pdf?martech=off

Update EdgeWorker code

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.md

testing process

---

acrobat/scripts/geo-phoneNumber.js
acrobat/scripts/scripts.js
package-lock.json
package.json
test/scripts/geo-phoneNumber.jest.js

Resolves - [MWPW-143726](https://jira.corp.adobe.com/browse/MWPW-143726)
Test:
https://mwpw-143726--dc--adobecom.hlx.page/

MWPW-143726

---

.kodiak/config.yaml

Add team assignment to kodiak tickets
- https://thedoc31-patch-2--dc--adobecom.hlx.page/?martech=off

Add team assignment

---

acrobat/blocks/eventwrapper/eventwrapper.js

Resolves: [MWPW-145916](https://jira.corp.adobe.com/browse/MWPW-145916)
The review widget and footer were hidden on upsell screen for fill&sign verb due to an experiment (they tested the fill&sign widget on full screen).
Now that the experiment is rolled back, we should display review widget and footer.

mwpw-145916 display review widget and footer on upsell screen

---

acrobat/blocks/personalization/personalization.css
acrobat/styles/styles.css

Resolves: [MWPW-146462](https://jira.corp.adobe.com/browse/MWPW-146462)

MWPW-146462

---

acrobat/blocks/eventwrapper/eventwrapper.css
acrobat/styles/styles.css

Resolves : [MWPW-146286](https://jira.corp.adobe.com/browse/MWPW-146286)
Test URL:
https://mwpw-146286--dc--adobecom.hlx.live/uk/acrobat/online/pdf-to-word?martech=off

MWPW-146286

---

.github/workflows/deploy-edgeworker.yml

Fix a workflow bug in the [previous PR](https://github.com/adobecom/dc/pull/645).

MWPW-145723 Fix EdgeWorker deployment workflow

---

acrobat/scripts/scripts.js

Resolves: [MWPW-147525](https://jira.corp.adobe.com/browse/MWPW-147525)
Test url:
[N/A](https://mwpw-147525--dc--adobecom.hlx.page/)

MWPW-147525: Remove Jarvis Surface ID Code for Metadata implementation

---

acrobat/scripts/scripts.js

[MWPW-148360](https://jira.corp.adobe.com/browse/MWPW-148360)

MWPW-148360 Fix locale ae_en

---

acrobat/blocks/interactive-marquee/interactive-marquee.css
acrobat/blocks/interactive-marquee/interactive-marquee.js

Resolves: [MWPW-148327](https://jira.corp.adobe.com/browse/MWPW-148327)
- [Figma file](https://www.figma.com/design/oaSS7IQHKv9d1d5kMhsF7t/11748238_DCPAS24_AGI_Simple-Interactive-Marquee-and-Acrobat-Discover-Mode_cm_v1?node-id=998-1863&t=zXLxwiNfD8bT6pNL-0)
Test URLs
Before:  https://main--dc--adobecom.hlx.page/drafts/rivero/MWPW-140704/interactive-marquee?martech=off
After: https://mwpw-148327--dc--adobecom.hlx.page/drafts/rivero/MWPW-148327/interactive-marquee?martech=off

MWPW-148327: Additional updates to interactive marquee

---

acrobat/blocks/interactive-marquee/interactive-marquee.css
acrobat/blocks/interactive-marquee/interactive-marquee.js

Special release DC MILO 1.2421 for : [MWPW-149225 ](https://jira.corp.adobe.com/browse/MWPW-149225)

DC MILO 1.2421

---

.github/workflows/fg-sync-repos.yml

MWPW-146848: Repo Sync Workflow for FG

---

acrobat/scripts/scripts.js
acrobat/styles/styles.css

Resolves: [MWPW-147913](https://jira.corp.adobe.com/browse/MWPW-147913)
Test URL: 
Before: https://main--dc--adobecom.hlx.page/acrobat/online/compress-pdf
After: https://mwpw-147913-loadims--dc--adobecom.hlx.page/acrobat/online/compress-pdf

Mwpw 147913 loadims

---

acrobat/scripts/scripts.js
acrobat/styles/styles.css

Resolves: [MWPW-147913](https://jira.corp.adobe.com/browse/MWPW-147913)
Test URL: https://mwpw-147913--dc--adobecom.hlx.page/
Before: https://main--dc--adobecom.hlx.page/acrobat/online/compress-pdf
After: https://mwpw-147913--dc--adobecom.hlx.page/acrobat/online/compress-pdf

MWPW-147913: Prevent users from uploading when they're signed in

---

acrobat/scripts/scripts.js

Resolves the `pps.read` portion of [MWPW-151553](https://jira.corp.adobe.com/browse/MWPW-151553)

MWPW-151553

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js

Test URL: https://instagram-fix-eol-redirect--dc--adobecom.hlx.live/acrobat/online/ai-chat-pdf

removed check for safari

---

acrobat/blocks/mobile-widget/mobile-widget.css
acrobat/blocks/mobile-widget/mobile-widget.js
acrobat/scripts/scripts.js

resolves: [MWPW-152920](https://jira.corp.adobe.com/browse/MWPW-152920)
Test links: 
https://mwpw-152920--dc--adobecom.hlx.page/acrobat/online/test/pdf-editor-mobile-widget
https://mwpw-152920--dc--adobecom.hlx.page/acrobat/online/test/request-signature-mobile-widget
https://mwpw-152920--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf-mobile-widget

MWPW-152920 built facade for get app for mobile widget

---

acrobat/blocks/mobile-widget/mobile-widget.css
acrobat/blocks/mobile-widget/mobile-widget.js

Resolves parts of [MWPW-152833](https://jira.corp.adobe.com/browse/MWPW-152833)

MWPW-152833

---

acrobat/scripts/scripts.js

`guest_token_force_refresh` added to `scripts.js` to support guest users

Added - guest_token_force_refresh 

---

acrobat/blocks/mobile-widget/mobile-widget.css
acrobat/scripts/scripts.js

Resolves: [MWPW-154007](https://jira.corp.adobe.com/browse/MWPW-154007)

Cherry-picked specific lines from stage

---

acrobat/scripts/scripts.js
acrobat/styles/styles.css

Revert "MWPW-147913: Prevent Users From Uploading When They're Signed In"

---

package-lock.json
package.json

Resolves: [MWPW-153983](https://jira.corp.adobe.com/browse/MWPW-153983)
Test URL:
https://mwpw-153983--dc--adobecom.hlx.page/

MWPW-153983: Upgrading async

---

acrobat/blocks/acom-widget/acom-widget.js
acrobat/blocks/acom-widget/pdfAssetManager.js

Resolves:
[MWPW-151232](https://jira.corp.adobe.com/browse/MWPW-151232)
[MWPW-151233](https://jira.corp.adobe.com/browse/MWPW-151233)
Test URL:
https://mwpw-151232--dc--adobecom.hlx.page/

MWPW-151232: SSRF prevention

---

acrobat/blocks/mobile-widget/mobile-widget.js
acrobat/scripts/alloy/mobile-widget-shown.js
acrobat/scripts/alloy/mobile-widget.js

Resolves : [MWPW-154356](https://jira.corp.adobe.com/browse/MWPW-154356)

MWPW-154356

---

package-lock.json
package.json

Resolves: [MWPW-152911](https://jira.corp.adobe.com/browse/MWPW-152911)
Test URL:
https://mwpw-152911--dc--adobecom.hlx.page/

MWPW-152911: ws upgrade

---

acrobat/blocks/mobile-widget/mobile-widget.js
acrobat/scripts/alloy/mobile-widget-shown.js
acrobat/scripts/alloy/mobile-widget.js

Test to validate [MWPW-154356](https://jira.corp.adobe.com/browse/MWPW-154356)

temp to test

---

acrobat/scripts/alloy/mobile-widget-shown.js
acrobat/scripts/alloy/mobile-widget.js

MWPW-154356 

---

test/e2e/features/regression/eventwrapper.feature
test/e2e/features/smoke/eventwrapper.feature
test/e2e/page-objects/commerce.section.js

Port changes @tedAir made to [Platform-UI-DC](https://git.corp.adobe.com/wcms/Platform-UI-DC)

Port changes from Platform-UI-DC

---

.gitignore

Resolves: [MWPW-155547](https://jira.corp.adobe.com/browse/MWPW-155547)
Test URL:
https://mwpw-155547--dc--adobecom.hlx.page

MWPW-155547: Adding .env to gitignore

---

.github/workflows/fg-sync-repos.yml
.github/workflows/graybox-sync-repos.yml

* Push sync for graybox and floodgate, skipping sync for excluded files.
Resolves: [MWPW-145389](https://jira.corp.adobe.com/browse/MWPW-145389)
**Example summary:**
- Stage: https://github.com/adobecom/milo/actions/runs/10166322730
- Main: https://github.com/adobecom/milo/actions/runs/10177206196

MWPW-145389 Push sync for graybox and floodgate

---

acrobat/scripts/contentSecurityPolicy/csp.js
acrobat/scripts/contentSecurityPolicy/dev.js
acrobat/scripts/contentSecurityPolicy/prod.js
acrobat/scripts/contentSecurityPolicy/stage.js

Resolves: [MWPW-154881](https://jira.corp.adobe.com/browse/MWPW-154881)
Test URL:
https://mwpw-154881--dc--adobecom.hlx.page/

MWPW-154881: CSP updates

---

acrobat/scripts/dcLana.js
acrobat/scripts/scripts.js
test/scripts/dcLana.test.js

Resolves: [MWPW-154878](https://jira.corp.adobe.com/browse/MWPW-154878)
Test URL:
https://mwpw-154878--dc--adobecom.hlx.page/acrobat/online/pdf-to-word

MWPW-154878: Removing key paring value from lana logs

---

test/blocks/mobile-widget/mocks/body.html

A mobile widget needs data-verb to initialize. It is added by scripts.js.

Fix test issue

---

package-lock.json
package.json

Resolves:
- [MWPW-155693](https://jira.corp.adobe.com/browse/MWPW-155693)
- [MWPW-155695](https://jira.corp.adobe.com/browse/MWPW-155695)
Test URL:
- https://mwpw-155693--dc--adobecom.hlx.page/

MWPW-155693: Upgrading deep-merge

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js

track performance for ims_guest rollout to compare widget loading time and time to interactivity

Turn on RUM collection from widget

---

acrobat/scripts/scripts.js

Resolves: [MWPW-156675](https://jira.corp.adobe.com/browse/MWPW-156675)

changed relative path with absolute

---

acrobat/scripts/contentSecurityPolicy/dev.js
acrobat/scripts/contentSecurityPolicy/prod.js
acrobat/scripts/contentSecurityPolicy/stage.js

DCXY-24832 Use more restrictive path, according to fedcm spec

---

acrobat/blocks/acom-widget/acom-widget.js

Resolves : [MWPW-154530](https://jira.corp.adobe.com/browse/MWPW-154530)

MWPW-154530

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js
test/blocks/dc-converter-widget/dc-converter-widget.jest.js

Revert "MWPW-156372"

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js
acrobat/scripts/alloy/mobile-widget-shown.js
acrobat/scripts/alloy/mobile-widget.js

Resolves : [MWPW-155492](https://jira.corp.adobe.com/browse/MWPW-155492)

MWPW-155492

---

acrobat/blocks/acom-widget/acom-widget.css
acrobat/blocks/acom-widget/acom-widget.js

Initial UI for Project Unity UI

Project Unity: New Block for UI

---

acrobat/blocks/acom-widget/acom-widget.css
acrobat/blocks/acom-widget/acom-widget.js
acrobat/blocks/acom-widget/limits.js

Initial work for MWPW-156303
merging now to unblock team

MWPW-156303

---

acrobat/blocks/acom-widget/acom-widget.css
acrobat/blocks/acom-widget/acom-widget.js

resolves: [MWPW-155784](https://jira.corp.adobe.com/browse/MWPW-155784)
test page: https://mwpw-155784-acom-widget-responsive--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf-projectunity

implemented responsive design for mobile widget

---

test/blocks/acom-widget/acom-widget-redirect.jest.js
test/blocks/acom-widget/acom-widget.jest.js
test/blocks/acom-widget/acom-widget.test.js
test/blocks/acom-widget/mocks/body.html
test/blocks/dc-converter-widget/dc-converter-widget.test.js

Fix unit tests

---

acrobat/blocks/mobile-widget/mobile-widget.js

https://mobile-widget-fix-pdf-editor-redirect--dc--adobecom.hlx.page/acrobat/online/pdf-editor

updated redirect link

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js

Resolves: [MWPW-157348](https://jira.corp.adobe.com/browse/MWPW-157348)
Test URL: https://mwpw-157348--dc--adobecom.hlx.page/acrobat/online/study-with-acrobat?app!versions=latest&verb=chat-pdf-student

MWPW-157348: Add Redirects for GoURL for new verb

---

acrobat/blocks/rnr/rnr.js

Resolves: [MWPW-156288](https://jira.corp.adobe.com/browse/MWPW-156288)
Test URL: https://mwpw-156288--dc--adobecom.hlx.page/drafts/astatescu/rnr/rnr-convert-pdf

MWPW-156288: rnr api integration, placeholders, json ld product info

---

acrobat/blocks/rnr/rnr.js

Resolves: [MWPW-157845](https://jira.corp.adobe.com/browse/MWPW-157845)
Test URL: https://mwpw-157845--dc--adobecom.hlx.page/acrobat/online/test/rnr-pdf-to-jpg

MWPW-157845: Fixed no aggregated rating message

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js
acrobat/blocks/unity/unity.js
acrobat/scripts/utils.js

Resolves: [MWPW-155563](https://jira.corp.adobe.com/browse/MWPW-155563)
Before: https://main--dc--adobecom.hlx.page/acrobat/online/test/unity-test?unitylibs=stage&martech=off
After: https://mwpw-155563-integrate-with-project-unity--dc--adobecom.hlx.page/acrobat/online/test/unity-test?unitylibs=stage&martech=off

implement integration with project unity

---

acrobat/blocks/rnr/rnr.js

Resolves: [MWPW-158034](https://jira.corp.adobe.com/browse/MWPW-158034)
Test URL: https://mwpw-158034--dc--adobecom.hlx.page/drafts/astatescu/rnr/

MWPW-158034: Integrate API changes for aggregated ratings

---

test/integration/table/mocks/body.html
test/integration/table/table_desktop.int.js
test/integration/table/table_mobile.int.js

resolves: [MWPW-147553](https://jira.corp.adobe.com/browse/MWPW-147553)

implemented integration test for table block

---

acrobat/blocks/verb-widget/verb-widget.js

Resolves : [MWPW-157982](https://jira.corp.adobe.com/browse/MWPW-157982)

MWPW-157982

---

acrobat/scripts/dcLana.js

Resolves: [MWPW-158520](https://jira.corp.adobe.com/browse/MWPW-158520)

MWPW-158520: Reducing sample rate for CSP

---

acrobat/scripts/scripts.js

Resolves : [MWPW-158445](https://jira.corp.adobe.com/browse/MWPW-158445)

MWPW-158445

---

acrobat/blocks/verb-widget/verb-widget.js

Resolves: [MWPW-159098](https://jira.corp.adobe.com/browse/MWPW-159098)
Signed-in Type 1 Users will be redirected to acrobat.adobe.com

MWPW-159098

---

acrobat/blocks/verb-widget/verb-widget.js

Minor update for [MWPW-158122](https://jira.corp.adobe.com/browse/MWPW-158122)

MWPW-158122

---

acrobat/blocks/verb-widget/verb-widget.js

Resolves : [MWPW-158477](https://jira.corp.adobe.com/browse/MWPW-158477)

MWPW-158477

---

acrobat/blocks/verb-widget/verb-widget.js

Resolves : [MWPW-159421](https://jira.corp.adobe.com/browse/MWPW-159421)

MWPW-159421

---

acrobat/scripts/alloy/verb-widget.js

Resolves : [MWPW-159560](https://jira.corp.adobe.com/browse/MWPW-159560)

MWPW-159560

---

acrobat/scripts/alloy/verb-widget.js

Revert "MWPW-159560"

---

acrobat/blocks/verb-widget/verb-widget.css
acrobat/blocks/verb-widget/verb-widget.js

Resolves: [MWPW-160606](https://jira.corp.adobe.com/browse/MWPW-160606), [MWPW-160613](https://jira.corp.adobe.com/browse/MWPW-160613) & [MWPW-160618](https://jira.corp.adobe.com/browse/MWPW-160618)
- Dropzone is not clickable
- Brand icon in landing page dropzone not visible on Safari
- TOU & Privacy Policy links should open in new tab

MWPW-160618, MWPW-160613, MWPW-160606

---

acrobat/blocks/verb-widget/verb-widget.css
acrobat/blocks/verb-widget/verb-widget.js

Resolves  : [MWPW-160689](https://jira.corp.adobe.com/browse/MWPW-160689)

MWPW-160689

---

acrobat/blocks/verb-widget/verb-widget.css
acrobat/blocks/verb-widget/verb-widget.js

Revert of [MWPW-160606](https://jira.corp.adobe.com/browse/MWPW-160606)

MWPW-160606

---

acrobat/blocks/verb-widget/verb-widget.js

Resolves: [MWPW-159559](https://jira.corp.adobe.com/browse/MWPW-159559)
Adds localizes links via getConfig and optional from place holders
**Test URL:**
Dynamic:
- Before:  https://main--dc--adobecom.hlx.page/it/acrobat/online/test/sign-pdf
- After: https://mwpw-159559--dc--adobecom.hlx.page/it/acrobat/online/test/sign-pdf
Optional by placeholders:
- Before:  https://main--dc--adobecom.hlx.page/mx/acrobat/online/test/sign-pdf
- After: https://mwpw-159559--dc--adobecom.hlx.page/mx/acrobat/online/test/sign-pdf
US - Default language:
- Before:  https://main--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf
- After: https://mwpw-159559--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf

MWPW-159559: Unity - Localize Legal URLs

---

acrobat/blocks/verb-widget/verb-widget.js

Resolves : [MWPW-160731](https://jira.corp.adobe.com/browse/MWPW-160731)
_I plan on optimizing this code next week_

MWPW-160731

---

acrobat/blocks/verb-widget/verb-widget.js

Resolves : [MWPW-160726](https://jira.corp.adobe.com/browse/MWPW-160726)

MWPW-160726

---

acrobat/blocks/verb-widget/verb-widget.js

Resolves: [MWPW-160726](https://jira.corp.adobe.com/browse/MWPW-160726)
Test URL: http://mwpw-160726--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf?martech=off

MWPW-160726: Implement Exit Prompt

---

acrobat/scripts/contentSecurityPolicy/prod.js
edgeworkers/Acrobat_DC_web_prod/utils/csp/prod.js

Resolves : [MWPW-161088](https://jira.corp.adobe.com/browse/MWPW-161088)

MWPW-161088

---

acrobat/blocks/verb-widget/verb-widget.js

Resolves: [MWPW-160251](https://jira.corp.adobe.com/browse/MWPW-160251)

MWPW-160251

---

acrobat/styles/styles.css

Resolves: [MWPW-161287](https://jira.corp.adobe.com/browse/MWPW-161287)
Test URL:
- Before: https://main--dc--adobecom.hlx.page/drafts/prativa/adobelogotestpage?milolibs=mwpw-160730--milo--deva309
- After: https://MWPW-161287--dc--adobecom.hlx.page/drafts/prativa/adobelogotestpage?milolibs=mwpw-160730--milo--deva309

MWPW-161287: Updated Adobe Logo is not appearing properly 

---

acrobat/blocks/prompt-card/prompt-card.js

Resolves: [MWPW-161334](https://jira.corp.adobe.com/browse/MWPW-161334)
**Test URL**
Before: https://stage--dc--adobecom.hlx.page/acrobat/generative-ai-pdf/resume-ai
Before on Stage: https://www.stage.adobe.com/acrobat/generative-ai-pdf/resume-ai.html
After: https://MWPW-161334--dc--adobecom.hlx.page/acrobat/generative-ai-pdf/resume-ai

MWPW-161334 Workaround Safari's ReferenceError when using a top-level await

---

acrobat/blocks/verb-widget/verb-widget.js

Resolves: [MWPW-162674](https://jira.corp.adobe.com/browse/MWPW-162674)
Test URL:
https://main--dc--adobecom.hlx.live/acrobat/online/sign-pdf
https://mwpw-162674--dc--adobecom.hlx.live/acrobat/online/sign-pdf

MWPW-162674: Adding properties available to Lana Logs for unity error handling

---

acrobat/scripts/contentSecurityPolicy/dev.js
acrobat/scripts/contentSecurityPolicy/prod.js
acrobat/scripts/contentSecurityPolicy/stage.js

Resolves: [MWPW-161240](https://jira.corp.adobe.com/browse/MWPW-161240)

MWPW-16240 Update CSP

---

acrobat/blocks/verb-widget/verb-widget.js

- Lana log if the redirect happens without cookie being set.
https://jira.corp.adobe.com/browse/MWPW-162758

MWPW-162758-Lana logging when cookie is not set

---

acrobat/scripts/susiAuthHandler.js

Resolves: [MWPW-161779](https://jira.corp.adobe.com/browse/MWPW-161779)
- Adds default link in to the anchor when user use the right click to open the link in new tab or window avoiding a 404
Test URL:
https://main--dc--adobecom.hlx.page/acrobat/online
https://mwpw-161779--dc--adobecom.hlx.page/acrobat/online

MWPW-161779: SUSI Link scenario when open in new tab or window

---

acrobat/blocks/mobile-widget/mobile-widget.js
acrobat/scripts/alloy/mobile-widget-shown.js
acrobat/scripts/alloy/mobile-widget.js
acrobat/styles/styles.css
test/blocks/mobile-widget/mobile-widget.test.js

Revert "MWPW-158083:  Mobile Widget - Acrobat exit modal "

---

acrobat/blocks/verb-widget/verb-widget.css

Resolves: [MWPW-164527](https://jira.corp.adobe.com/browse/MWPW-164527)
Before: https://stage--dc--adobecom.hlx.page/acrobat/online/test/compress-pdf
After: https://mwpw-164527-fix--dc--adobecom.hlx.page/acrobat/online/test/compress-pdf

MWPW-164527: Hot fix - Flex direction & padding

---

helix-query.yaml
helix-sitemap.yaml

Add the il_he locale sitemap back
Resolves: [MWPW-165598](https://jira.corp.adobe.com/browse/MWPW-165598)

MWPW-165598 Add il_he sitemap

---

acrobat/blocks/rnr/rnr.css
acrobat/blocks/rnr/rnr.js
acrobat/scripts/susiAuthHandler.js
acrobat/scripts/utils.js

Includes:
- Validation of options
- Fixed some labels in case where placeholders were missing
- Preloading star icons (there was an issue where the first time the user landed on the page and hovered the rating stars, it would take a bit for the filled star image to load)
- Removed the need to add the `Title` option with the placeholder text (`{{rnr-title}}`) on the authoring side, loading placeholders in code
Resolves: [MWPW-165647](https://jira.corp.adobe.com/browse/MWPW-165647)
Test URL: https://mwpw-165647--dc--adobecom.hlx.page/drafts/astatescu/rnr/
NOTE: Loading and persisting ratings only works on stage, where there's a valid ims token.

MWPW-165647: Rnr cleanup

---

acrobat/blocks/prompt-card/prompt-card.css
acrobat/blocks/prompt-card/prompt-card.js

- MWPW-164412 Status message not automatically announced - copy to clipboard
- MWPW-163870 Controls have same name but different actions - copy
Test URL: 
https://main--dc--adobecom.hlx.live/acrobat/generative-ai-pdf
https://mwpw164412and163870--dc--bozojovicic.hlx.live/acrobat/generative-ai-pdf

MWPW-164412 and MWPW-163870 A11Y Copy to clipboard

---

acrobat/blocks/susi-light/susi-light.js

Revert "MWPW-165584 Use DC's client ID for SUSI Light"

---

acrobat/blocks/verb-widget/verb-widget.css

Resolves: [MWPW-165703](https://jira.corp.adobe.com/browse/MWPW-165703)
Fix icon position 
Test URL:
https://main--dc--adobecom.hlx.page/acrobat/online/compress-pdf
https://mwpw-165703-icon-position--dc--adobecom.hlx.page/acrobat/online/compress-pdf

MWPW-165703: Fix (i) Icon position

---

acrobat/blocks/verb-widget/verb-widget.js

Resolve: [MWPW-165868](https://jira.corp.adobe.com/browse/MWPW-165868)

MWPW-165868 Add analytics events for upsell

---

acrobat/blocks/rnr/rnr.js
acrobat/blocks/verb-widget/verb-widget.css
acrobat/blocks/verb-widget/verb-widget.js

Adjusted the layout to restore proper alignment and spacing for verb-widget

DC Milo 2.504 fix

---

acrobat/scripts/scripts.js

Test URL:
- Before: https://main--dc--adobecom.hlx.page/acrobat/online/sign-pdf
- After: https://mwpw-166351--dc--adobecom.hlx.page/acrobat/online/sign-pdf

MWPW-166351: IMSS call to support UNav 1.4

---

acrobat/scripts/alloy/verb-widget.js

Resolves: 
- [MWPW-167048](https://jira.corp.adobe.com/browse/MWPW-167048)
- [MWPW-167047](https://jira.corp.adobe.com/browse/MWPW-167047)
- [MWPW-167046](https://jira.corp.adobe.com/browse/MWPW-167046)
**Test URL**
- Before: https://main--dc--adobecom.hlx.page/acrobat/online/sign-pdf
- After: https://mwpw-167048--dc--adobecom.hlx.page/acrobat/online/sign-pdf

MWPW-167048: Removing success events reported to lana

---

acrobat/blocks/verb-widget/limits.js
acrobat/blocks/verb-widget/verb-widget.js

Resolves: [MWPW-166142](https://jira.corp.adobe.com/browse/MWPW-166142)
**Test URL**
Before:
- https://main--dc--adobecom.hlx.page/acrobat/online/sign-pdf
- https://main--dc--adobecom.hlx.page/acrobat/online/compress-pdf
After:
- https://mwpw-166142--dc--adobecom.hlx.page/acrobat/online/sign-pdf
- https://mwpw-166142--dc--adobecom.hlx.page/acrobat/online/compress-pdf

MWPW-166142: Adding multifile-only CTA

---

acrobat/blocks/rnr/rnr.js

Resolves: [MWPW-167548](https://jira.corp.adobe.com/browse/MWPW-167548)
Current: https://main--dc--adobecom.hlx.page/acrobat/online/word-to-pdf
Test URL: https://mwpw-167548--dc--adobecom.hlx.page/acrobat/online/word-to-pdf

MWPW-167548: Transient api key

---

acrobat/blocks/rnr/rnr.js

Resolves: [MWPW-167548](https://jira.corp.adobe.com/browse/MWPW-167548)
Current: https://main--dc--adobecom.hlx.page/acrobat/online/word-to-pdf
Test URL: https://mwpw-167548--dc--adobecom.hlx.page/acrobat/online/word-to-pdf

MWPW-167548: POST request api key fix

---

acrobat/blocks/verb-widget/verb-widget.js

Resolves: [MWPW-168174](https://jira.corp.adobe.com/browse/MWPW-168174)
Test URLs:
Before: https://stage--dc--adobecom.hlx.page/acrobat/online/split-pdf
After: https://mwpw-168174--dc--adobecom.hlx.page/acrobat/online/split-pdf

MWPW-168174: Adding error_min_page_count

---

.kodiak/config.yaml

Resolves:
- [MWPW-147863](https://jira.corp.adobe.com/browse/MWPW-147863)
- [MWPW-147862](https://jira.corp.adobe.com/browse/MWPW-147862)
**Test URLs:**
- https://main--dc--adobecom.hlx.page/
- https://mwpw-147862--dc--adobecom.hlx.page/

MWPW-147863: Excluding edge workers folder in kodiak

---

acrobat/blocks/verb-widget/verb-widget.js

Revert "MWPW-169069: Multi-file events enablement across all verbs"

---

acrobat/scripts/scripts.js

Resolves : [MWPW-169627](https://jira.corp.adobe.com/browse/MWPW-169627)
**Test URLs**
Before: https://stage--dc--adobecom.hlx.page/jp/acrobat 
After: https://fixdotmedia--dc--adobecom.hlx.page/jp/acrobat
The bug is on the stage https://www.stage.adobe.com/jp/acrobat.html. It can't be tested on the hlx domain.

MWPW-169627 Fix replaceDotMedia for ROW

---

acrobat/scripts/contentSecurityPolicy/dev.js
acrobat/scripts/contentSecurityPolicy/prod.js
acrobat/scripts/contentSecurityPolicy/stage.js
head.html

Resolves: [MWPW-169634](https://jira.corp.adobe.com/browse/MWPW-169634)
**Test URLs**
Before: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf
After: https://MWPW-169634--dc--adobecom.hlx.page/acrobat/online/compress-pdf

MWPW-169634 Fix preload for CSS and SVG

---

acrobat/scripts/scripts.js

Resolves: [MWPW-169776](https://jira.corp.adobe.com/browse/MWPW-169776)
**Test URLs:**
- https://main--dc--adobecom.hlx.page/
- https://mwpw-169776--dc--adobecom.hlx.page/

MWPW-169776: Add IMS scope configuration warning notice

---

acrobat/scripts/alloy/verb-widget.js

Resolves: [MWPW-169158](https://jira.corp.adobe.com/browse/MWPW-169158)
**Test URLs**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf
- After: https://mwpw-169158-update--dc--adobecom.hlx.page/acrobat/online/compress-pdf

MWPW-169158: Verb Widget Analytics Code Optimization

---

acrobat/scripts/contentSecurityPolicy/dev.js
acrobat/scripts/contentSecurityPolicy/prod.js
acrobat/scripts/contentSecurityPolicy/stage.js
head.html

Revert "MWPW-169654 Optimizing Body Hiding for better Indexing and SEO"

---

acrobat/blocks/verb-widget/verb-widget.css

Resolves : [MWPW-169884](https://jira.corp.adobe.com/browse/MWPW-169884)

MWPW-169884

---

.github/pull_request_template.md

Resolves: [MWPW-170097](https://jira.corp.adobe.com/browse/MWPW-170097)

MWPW-170097: Adding template to improve PR creation process

---

acrobat/blocks/verb-widget/verb-widget.js
acrobat/scripts/alloy/verb-widget.js

Resolves: [MWPW-170574](https://jira.corp.adobe.com/browse/MWPW-170574)
- http://mwpw-170574-update--dc--adobecom.aem.page/acrobat/online/compress-pdf

MWPW-170574-update

---

acrobat/scripts/contentSecurityPolicy/dev.js
acrobat/scripts/contentSecurityPolicy/prod.js
acrobat/scripts/contentSecurityPolicy/stage.js

Korean page has a www.youtube-nocookie.com link.
Resolves: [MWPW-169760](https://jira.corp.adobe.com/browse/MWPW-169760)
- https://main--dc--adobecom.hlx.page/kr/acrobat/online/merge-pdf
- http://mwpw-169760--dc--adobecom.aem.page/kr/acrobat/online/merge-pdf

MWPW-169760 Add www.youtube-nocookie.com to CSP

---

acrobat/blocks/verb-widget/verb-widget.js
acrobat/scripts/alloy/verb-widget.js

One more test for AA
Resolves: [MWPW-170574](https://jira.corp.adobe.com/browse/MWPW-170574)
- http://mwpw-170574--dc--adobecom.aem.page/acrobat/online/compress-pdf

MWPW-170574

---

acrobat/blocks/verb-widget/verb-widget.js
acrobat/scripts/alloy/verb-widget.js

We will dispatch an event when the analytics `done` callback is satisfied OR 3 seconds have elapsed for the `job:uploaded` event.
Event name `DCUnity:RedirectReady` 
Once dispatched Unity may redirect to DC Web
Resolves: [MWPW-170574](https://jira.corp.adobe.com/browse/MWPW-170574)
- http://mwpw-170574--dc--adobecom.aem.page/acrobat/online/compress-pdf

MWPW-170574 fix from AA team

---

acrobat/blocks/verb-widget/verb-widget.js
acrobat/scripts/alloy/verb-widget.js

MWPW-170574 fixes

---

acrobat/scripts/contentSecurityPolicy/dev.js
acrobat/scripts/contentSecurityPolicy/prod.js
acrobat/scripts/contentSecurityPolicy/stage.js

Add i.ytimage.com to CSP
Resolves: [MWPW-170767](https://jira.corp.adobe.com/browse/MWPW-170767)
- Before: http://main--dc--adobecom.aem.page/kr/acrobat/online/merge-pdf
- After: http://mwpw-170767--dc--adobecom.aem.page/kr/acrobat/online/merge-pdf
There should be an image on the embedded YouTube video.

MWPW-170767 Add i.ytimg.com to CSP

---

.github/workflows/graybox-sync-repos.yml

Fixes repo-sync issue for Graybox git action.
Resolves: [MWPW-170940](https://jira.corp.adobe.com/browse/MWPW-170940)
- http://fix-sync--dc--adobecom.aem.page/acrobat/online/compress-pdf

MWPW-170940: Fix graybox repo-sync issue

---

acrobat/styles/styles.css

Fix the CLS caused by new gnav in pre unity pages
Resolves: [MWPW-170166](https://jira.corp.adobe.com/browse/MWPW-170166)
- http://main--dc--adobecom.hlx.page/acrobat/online/sign-pdf
- http://mwpw-170166--dc--adobecom.hlx.page/acrobat/online/sign-pdf
- http://main--dc--adobecom.hlx.page/acrobat/online/word-to-pdf
- http://mwpw-170166--dc--adobecom.hlx.page/acrobat/online/word-to-pdf

MWPW-170166: CLS fix with for new gnav

---

acrobat/blocks/verb-widget/verb-widget.js
acrobat/scripts/alloy/verb-widget.js

Changes done on the event "unity:track-analytics"  fired from unity
Create event object similar to how we do for AA logging. 
https://jira.corp.adobe.com/browse/MWPW-171256

[MWPW-171256] Send AA events to Lana from unity

---

acrobat/blocks/verb-widget/verb-widget.js

Test and bug fix from bad merge 
Resolves: [MWPW-171007](https://jira.corp.adobe.com/browse/MWPW-171007)
- http://mwpw-171007--dc--adobecom.aem.page/acrobat/online/compress-pdf

MWPW-171007

---

acrobat/blocks/verb-widget/verb-widget.js
acrobat/scripts/alloy/verb-widget.js

In order to track analytics for engineering, we have spun up a service to relay analytics to splunk index. This PR contains the changes to integrate this api to send the analytics to splunk. Also have customised the event payload as per the engineering needs. 
https://jira.corp.adobe.com/browse/MWPW-171322

Changes to send analytics to splunk + refatoring changes from reverted PR 1093

---

acrobat/blocks/verb-widget/verb-widget.js

Fix for isMultiFile not defined

---

acrobat/blocks/verb-widget/verb-widget.js
acrobat/scripts/alloy/verb-widget.js

Fixing for undefined errorCode

---

acrobat/scripts/alloy/verb-widget.js

Fixing the headers in fetch call

---

acrobat/blocks/verb-widget/verb-widget.css

Resolves:
- [MWPW-170065](https://jira.corp.adobe.com/browse/MWPW-170065)
- [MWPW-171070](https://jira.corp.adobe.com/browse/MWPW-171070)
- http://main--dc--adobecom.hlx.page/fr/acrobat/online/compress-pdf
- http://mwpw-170065--dc--adobecom.hlx.page/fr/acrobat/online/compress-pdf

MWPW-170065: This address the issue with the h1 and desc, pre-wrapping the CTA button

---

acrobat/blocks/verb-widget/verb-widget.js
acrobat/scripts/alloy/verb-widget.js

Service endpoint configuration basis the env + flag to control whether to send events to splunk

---

acrobat/blocks/verb-widget/verb-widget.js
acrobat/scripts/alloy/verb-widget.js

Endpoint was not sent to alloy for error analytics to splunk. Fixed it

Splunk endpoint fix

---

helix-query.yaml

Experiment - See if we can build a query of unity pages to make managing metadata easier

add query for unity

---

.github/workflows/metadata-published.yml
.github/workflows/page-published.yml
.github/workflows/smoke-test.yml
.github/workflows/test-edgeworker.yml
.github/workflows/test-ing.yml
.github/workflows/test-milo.yml

Update actions/upload-artifact version
Resolves: [MWPW-171487](https://jira.corp.adobe.com/browse/MWPW-171487)
It's an update of workflows. Test URLs are not applicable.

MWPW-171487 Update actions/upload-artifact version

---

acrobat/blocks/verb-widget/verb-widget.css

Resolves: [MWPW-170309](https://jira.corp.adobe.com/browse/MWPW-170309)
- http://main--dc--adobecom.aem.page/acrobat/online/add-pdf-page-numbers
- http://mwpw-170309--dc--adobecom.aem.page/acrobat/online/add-pdf-page-numbers
- http://main--dc--adobecom.aem.page/acrobat/online/sign-pdf
- http://mwpw-170309--dc--adobecom.aem.page/acrobat/online/sign-pdf
- http://stage--dc--adobecom.aem.page/tr/acrobat/online/add-pdf-page-numbers
- http://mwpw-170309--dc--adobecom.aem.page/tr/acrobat/online/add-pdf-page-numbers

MWPW-170309: Fixing Start free trial and get app CTA's

---

acrobat/blocks/verb-widget/verb-widget.js

Fix analytics init by capturing original no‑op stubs and validating post‑load replacements—logging to Lana if any stub remains—and cleaned up related lint errors.
Resolves: [MWPW-171714](https://jira.corp.adobe.com/browse/MWPW-171714)
- http://main--dc--adobecom.hlx.page/acrobat/online/compress-pdf
- http://mwpw-171714--dc--adobecom.hlx.page/acrobat/online/compress-pdf

MWPW-171714: Adding lana logs when analytics function remain empty

---

acrobat/scripts/scripts.js
helix-query.yaml

Resolves: [MWPW-170932](https://jira.corp.adobe.com/browse/MWPW-170932)
- http://mwpw-170932--dc--adobecom.aem.page/acrobat/online/compress-pdf

MWPW-170932

---

.github/workflows/prerender-check-stage.yml
.github/workflows/prerender-check.yml
.github/workflows/prerender-create-bulk.yml
.github/workflows/prerender-create-stage-bulk.yml
.github/workflows/prerender-create-stage.yml
.github/workflows/prerender-create.yml
.github/workflows/prerender-delete.yml
.github/workflows/prerender-list.yml
.github/workflows/prerender-read.yml
.github/workflows/test-page-published.yml
package-lock.json
package.json
tools/preredner/README.md
tools/preredner/dev-server.config.mjs
tools/preredner/edgekv.ipynb
tools/preredner/prerender-gist.js
tools/preredner/prerender.js
tools/preredner/screenshot-gist.js
tools/preredner/screenshot.js

- Add scripts to generate a preredered snippet to be inserted into the HTML page
- Add scripts to take screenshots for verification of snippet injection
- Add workflows to manage EdgeKV items and generate prerendered snippets for production  
Resolves: [MWPW-170391](https://jira.corp.adobe.com/browse/MWPW-170391)
No product code change

MWPW-170391 Prerender services

---

test/blocks/dc-converter-widget/dc-converter-widget-error.test.js
test/blocks/dc-converter-widget/dc-converter-widget.test.js
test/edgeworkers/Acrobat_DC_web_prod/main.jest.js
test/edgeworkers/__mocks__/request.js
test/edgeworkers/__mocks__/response-verb-widget-styles.js
test/edgeworkers/__mocks__/text-encode-transform.js

- Code changes from DC Widget error handling and EdgeWorker cause unit test failures
- The coverage improvement will be addressed in another ticket. 
N/A

Fix failed unit tests

---

acrobat/scripts/alloy/verb-widget.js

Added chunkNumber, assetId and maxRetryCount to chunk uploaded and file uploaded events

---

acrobat/scripts/threeInOne.js

3-n-1 fix
Resolves: [MWPW-172568](https://jira.corp.adobe.com/browse/MWPW-172568)
- http://mwpw-172568--dc--adobecom.aem.page/acrobat/online/compress-pdf

MWPW-172568

---

acrobat/blocks/verb-widget/verb-widget.css

Responsive min-sizes for desktop and spaces for free trial CTA, padding for desktop
Resolves: [MWPW-173338](https://jira.corp.adobe.com/browse/MWPW-173338)
- http://mwpw-173338--dc--adobecom.aem.page/acrobat/online/compress-pdf

MWPW-173338: Verb widget consonant compliant fixes

---

acrobat/blocks/verb-widget/verb-widget.js

Limits for
- Merge / Combine PDF
- Rotate PDF Pages
- Protect PDF
Resolves: [MWPW-172187](https://jira.corp.adobe.com/browse/MWPW-172187)
- https://mwpw-172187--dc--adobecom.aem.live/acrobat/online/compress-pdf

MWPW-172187

---

acrobat/blocks/rnr/rnr.js
test/blocks/rnr/rnr.test.js

Fixes token if IMS is not loaded in the RnR component and retries after 1s and catch and logs messages on lana
Resolves: [MWPW-173376](https://jira.corp.adobe.com/browse/MWPW-173376)
- https://mwpw-173376--dc--adobecom.aem.live/acrobat/online/compress-pdf

MWPW-173376: Fix for RnR errors & handling IMS

---

acrobat/blocks/rnr/rnr.js
test/blocks/rnr/rnr.test.js

- https://mwpw-XXXXXX--dc--adobecom.aem.live/acrobat/online/compress-pdf

MWPW-173376

---

acrobat/blocks/rnr/rnr.js

- https://mwpw-XXXXXX--dc--adobecom.aem.live/acrobat/online/compress-pdf

Adding better ratio on lana logs and message

---

acrobat/blocks/verb-widget/verb-widget.js

Resolves: [MWPW-173455](https://jira.corp.adobe.com/browse/MWPW-173455)
https://stage--dc--adobecom.hlx.page/acrobat/online/test/unity/merge-pdf?unitylibs=batch2b

Update error codes for 2b, 2a

---

acrobat/blocks/verb-widget/verb-widget.js

Allow multi-file upload
Resolves: [MWPW-173691](https://jira.corp.adobe.com/browse/MWPW-173691)
- https://mwpw-173691--dc--adobecom.aem.live/acrobat/online/compress-pdf

MWPW-173691

---

acrobat/blocks/verb-widget/verb-widget.js

Update verb configs for Merge PDF, Chat with your PDF, and Study with Acrobat. 
Resolves: [MWPW-173733](https://jira.corp.adobe.com/browse/MWPW-173733) and [MWPW-173697](https://jira.corp.adobe.com/browse/MWPW-173697)
- https://mwpw-173733--dc--adobecom.aem.live/acrobat/online/compress-pdf

MWPW-173733 Update verb configs

---

acrobat/scripts/threeInOne.js

3-in-1 updated mappings
Resolves: [MWPW-173417](https://jira.corp.adobe.com/browse/MWPW-173417)
- https://mwpw-173417--dc--adobecom.aem.live/acrobat/online/compress-pdf

MWPW-173417

---

acrobat/blocks/verb-widget/verb-widget.js

Remove the legal message for verbs on Mobile with the Get App button
Resolves: [MWPW-173775](https://jira.corp.adobe.com/browse/MWPW-173775)
- https://main--dc--adobecom.aem.live/acrobat/online/sign-pdf
- https://mwpw-173775--dc--adobecom.aem.live/acrobat/online/sign-pdf

MWPW-173775 No legal message for Get App

---

acrobat/blocks/verb-widget/verb-widget.js

Remove generic errors with more specific ones. Catch failures at more granular level to categorise them into pre upload and upload errors.
Corresponding unity PR: https://github.com/adobecom/unity/pull/426 
Also, before sending cancel event, check if terminal event is already sent
Resolves: [MWPW-173667](https://jira.corp.adobe.com/browse/MWPW-173667) and [MWPW-173671](https://jira.corp.adobe.com/browse/MWPW-173671)
- https://mwpw-173667--dc--adobecom.aem.live/acrobat/online/compress-pdf

[MWPW-173667] Split generic errors

---

acrobat/blocks/verb-widget/verb-widget.js

PRs:
- https://github.com/adobecom/dc/pull/1193 
- https://github.com/adobecom/dc/pull/1201
- https://github.com/adobecom/dc/pull/1187
- https://github.com/adobecom/dc/pull/1174
- https://release-052225-unity--dc--adobecom.aem.live/acrobat/online/compress-pdf

Release branch for unity changes

---

acrobat/blocks/verb-widget/verb-widget.css

fix dz fix

---

acrobat/blocks/verb-widget/verb-widget.css

Tablet bug fix

---

package-lock.json
test/blocks/verb-widget/verb-widget.test.js

Fix unit test

---

acrobat/blocks/verb-widget/verb-widget.js

Resolves: [MWPW-174349](https://jira.corp.adobe.com/browse/MWPW-174349)
- https://mwpw-174349--dc--adobecom.aem.live/acrobat/online/compress-pdf

MWPW-174349 (Refactor)

---

acrobat/blocks/verb-widget/verb-widget.js

Batch 1a support for signed-in `type1` users 
```
https://www.adobe.com/acrobat/online/pdf-editor.html
https://www.adobe.com/acrobat/online/split-pdf.html
https://www.adobe.com/acrobat/online/crop-pdf.html
https://www.adobe.com/acrobat/online/add-pdf-page-numbers.html
```
Resolves: [MWPW-175358](https://jira.corp.adobe.com/browse/MWPW-175358)
- https://mwpw-175358--dc--adobecom.aem.live/acrobat/online/compress-pdf

MWPW-175358

---

acrobat/blocks/verb-widget/verb-widget.js

Fix to prevent sending duplicate events when the solo upload CTA is clicked
- https://mwpw-XXXXXX--dc--adobecom.aem.live/acrobat/online/compress-pdf

dup aa fix

---

tools/notebooks/listEDSFiles.ipynb

Notebook for listing live and preview pages on EDS
[MWPW-175363](https://jira.corp.adobe.com/browse/MWPW-175363)
N/A

MWPW-175363 Notebook for listing EDS pages

---

acrobat/blocks/verb-widget/verb-widget.js

Resolves: [MWPW-177168](https://jira.corp.adobe.com/browse/MWPW-177168)
- https://mwpw-177168--dc--adobecom.aem.live/acrobat/online/compress-pdf

Revert "MWPW-177168 Hide sticky CTA for mobile and tablet"

---

acrobat/blocks/dc-merch-card-checkbox/dc-merch-card-checkbox.js

Fixed AI checkbox issue for BR page
Resolves: [MWPW-177346](https://jira.corp.adobe.com/browse/MWPW-177346)
- https://main--dc--adobecom.aem.page/br/acrobat/generative-ai-pdf
- https://mwpw-177346-hotfix--dc--adobecom.aem.page/br/acrobat/generative-ai-pdf

[MWPW-177346]: added hot fix for AI checkbox

---

acrobat/blocks/verb-widget/verb-widget.css
acrobat/styles/styles.css

Resolves: [MWPW-179684](https://jira.corp.adobe.com/browse/MWPW-179684)
- https://main--dc--adobecom.aem.live/acrobat/online/ai-summary-generator
- https://mwpw-179684x--dc--adobecom.aem.live/acrobat/online/ai-summary-generator
- https://main--dc--adobecom.aem.live/de/acrobat/online/ai-summary-generator
- https://mwpw-179684x--dc--adobecom.aem.live/de/acrobat/online/ai-summary-generator

MWPW-179684x: Fix Heading breaking by word
