adobecom/dc

acrobat/scripts/scripts.js

see https://github.com/adobecom/milo-college/pull/5
Before: https://main--acrobat--adobecom.hlx.page/acrobat/
After: https://mwpw-121309--acrobat--adobecom.hlx.page/acrobat/

move await call inside asynchronous function for <= safari 14

---

acrobat/scripts/legacyBrowser.js
acrobat/scripts/scripts.js

Checks if Browser is:
- Safari >= 14
- Edge >= 86
otherwise redirect to https://acrobat.adobe.com/home/index-browser-eol.html
Before : https://main--acrobat--adobecom.hlx.page/acrobat/online/pdf-to-ppt
After : https://mwpw-120007--acrobat--adobecom.hlx.page/acrobat/online/pdf-to-ppt
Note for testing:
- Testing lower then Safari 13.1 (labeled as 13 in SauceLabs) or Edge  80 will not work, as milo itself will fail to load.

Mwpw 120007 Legacy Browser redirect

---

acrobat/blocks/personalization/personalization.js

Before:  https://main--acrobat--adobecom.hlx.page/acrobat/online/pdf-to-ppt
After:  https://mwpw-123753--acrobat--adobecom.hlx.page/acrobat/online/pdf-to-ppt
To test: See step by step description in https://jira.corp.adobe.com/browse/MWPW-123753

MWPW-123753 Review component spacing is being held when viewing the conversion complete screen

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js

The pre-rendered document we are fetching is actually an HTML document with both a Style tag and a div with the content.  In order for React hydration to work, the DOM needs to match what is ultimately rendered, which means just the div part needs to be added to the widgetContainer.  We can put the Style tag directly in the head.
@Blainegunn

use DOMParser instead of innerHTML

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.css
acrobat/styles/styles.css

There was some missmatch in CSS for the browser extension modal dialog, e.g. the button would appear as a link , see orginal issue : https://jira.corp.adobe.com/browse/MWPW-125150
Before: https://main--dc--adobecom.hlx.page/dc-shared/fragments/shared-fragments/browser-extension/browser-extension-edge
https://main--dc--adobecom.hlx.page/dc-shared/fragments/shared-fragments/browser-extension/browser-extension-chrome
After: https://mwpw-125150--dc--adobecom.hlx.page/dc-shared/fragments/shared-fragments/browser-extension/browser-extension-edge
https://mwpw-125150--dc--adobecom.hlx.page/dc-shared/fragments/shared-fragments/browser-extension/browser-extension-chrome

MWPW-125150 cleanup CSS for browser extension modal

---

acrobat/styles/styles.css

Fixed the size of the browser extension modal to be the same as what is currently online.
Whats live: https://www.adobe.com/acrobat/online/pdf-to-ppt.html
Before: https://main--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt
After: https://mwpw-125163--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt
To test:
- Open an incognito window
- upload one file
=> after upload the modal should appear bottom left

MWPW-125163 Fixed size of browser extension modal

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.css

See https://jira.corp.adobe.com/browse/MWPW-123750
Fixed salom background to always be large enough in desktop, tablet, mobile view so that the widget does not overlap the  text that comes afterwards:
Before: https://main--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt
After: https://mwpw-123750--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt

MWPW-123750 fix salmon background

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.css

merging `main` branch into this [PR ](https://github.com/adobecom/dc/pull/102) somehow brought back the dublicate `.dc-wrapper `entry:
Before: https://main--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt
After: https://mwpw-123750-2--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt
there should be no difference before and after:
- upload a file 
- use browser console device toggle to resize window
-  the widget should still not overlap the text that comes after.

remove dublicate .dc-wrapper CSS

---

acrobat/scripts/contentSecurityPolicy/prod.js
acrobat/scripts/contentSecurityPolicy/stage.js

The CSP files for stage and prod are not using single quotes for keywords like 'self', 'unsafe-eval'.
See : https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/Sources
Before; https://main--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt
After: https://csp-use-single-quotes--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt
NOTE: the above cant be compared since main used prod CSP and the branch uses dev CSP

CSP requires single quotes for keywords

---

.github/workflows/run-nala.yml

added github action to run nala tests on PRs
To fully make this work desired labels for filtering tests will need to be made on the repository using Nala, i.e., '@converter'
Also, another label named 'run-nala' will need to be added to the repository so developers can add it to their PRs for the nala tests to execute.
Second to help stop a lot of failures if by accident a developer doesn't select a filter label in addition to the 'run-nala' label to GitHub Secrets will need to be added for the IMSLogin Test.

added github action to run nala tests on PRs

---

acrobat/styles/styles.css

Font in FAQ section colored in blue instead of black. The issue is seen on both mobile & iPad devices.
Looks like some weird apple specific behavior on their devices, see e.g. https://developer.apple.com/forums/thread/690529.
Setting the color explicity solves the issue:
IPad
IPhone
Before: https://main--dc--adobecom.hlx.page/drafts/msagolj/live-test-pdf-to-ppt
After: https://mwpw-125486--dc--adobecom.hlx.page/drafts/msagolj/live-test-pdf-to-ppt
NOTE:
To Test you have to use a real apple device or one from saucelabs: https://app.saucelabs.com/live/web-testing/device

MWPW-125486 Set explicit color for Accordion button to black

---

.github/workflows/run-nala.yml

Added repo name variable so we can distinguish which site's repo Nala is running against for PRs.
This additional variable will send it the particular repository name which will be pulled out in order to set up the URLs correctly for feature branches on consumer sites running Nala against their own repositories.
Resolves: [MWPW-125473](https://jira.corp.adobe.com/browse/MWPW-125473)
Related Nala PR that will use this change for the Frictionless Team/DC Site: https://github.com/adobecom/nala/pull/61
Related Milo PR: https://github.com/adobecom/milo/pull/475

GitHub Actions new variable for PR testing with Nala

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js

Updates version for generate-cache to  correct version (1.163.1 vs 1.165.0) - per @JFernandezAdobe request on the ticket.
Added mappings for dynamically generated redirect urls (since for some verbs they are not following pattern and VERB.split('-').join('') would not give correct result, for example: for verb crop-pages, redirect url should be https://www.adobe.com/go/acrobat-crop and not https://www.adobe.com/go/acrobat-croppages, as for verbs extract-pages,combine-pdf,protect-pdf

Mwpw 125812 update

---

acrobat/styles/styles.css

https://jira.corp.adobe.com/browse/MWPW-127980
Before: https://main--dc--adobecom.hlx.page/acrobat/hub/how-to/10-benefits-of-digitizing-documents
After: https://mwpw-127980-add-missing-css-to-short-pages--dc--adobecom.hlx.page/acrobat/hub/how-to/10-benefits-of-digitizing-documents

MWPW-127980: Added css for reading-width

---

acrobat/scripts/scripts.js

Moving the dcLana import right before the function get called so loadArea() doesn't have to wait the file get loaded.
before: https://stage--dc--adobecom.hlx.live/acrobat/online/pdf-to-ppt
after: https://lana--dc--adobecom.hlx.live/acrobat/online/pdf-to-ppt

Improving LCP first load time.

---

acrobat/scripts/utils.js

Resolve: https://jira.corp.adobe.com/browse/MWPW-128105
According from the @JFernandezAdobe requirement, files which were coming from _main-milo-adobecom.hlx.page_ before, now are coming from  _www.adobe.com_. 
With this change, www.stage.adobe.com will use production code (www.adobe.com), but with _?milolibs_ param it can be set to use _main--milo--adobecom.hlx.page/libs_ or _localhost/libs_.
I put the label 'do not merge' because I need confirmation that libs should come from _www.adobe.com_ and not from _http://www.stage.adobe.com_
Test URLs (test once the changes are published):
- https://www.stage.adobe.com/acrobat/online/jpg-to-pdf.html
- https://www.stage.adobe.com/acrobat/online/jpg-to-pdf.html?milolibs=local (milo should be run locally)
- …

MWPW-128105 - stage.adobe.com + MILO libs

---

.github/workflows/run-inside.yml

* POC that GitHub Actions can trigger inside tests on the corp CircleCI and Jenkins.
* The trigger events are the same as the unit test's.
* CCI_TOKEN, JNK_USER, JNK_API_TOKEN, and JNK_JOB_TOKEN should be set in the repo's GitHub Actions secrets.

MWPW-128729 trigger inside tests

---

acrobat/blocks/promotion/promotion.js
acrobat/scripts/scripts.js

Resolve: [MWPW-129216](https://jira.corp.adobe.com/browse/MWPW-129216)
Before: https://stage--dc--adobecom.hlx.page/acrobat/hub/how-to/how-to-convert-pdf-to-image
After: https://delay-promotion--dc--adobecom.hlx.page/acrobat/hub/how-to/how-to-convert-pdf-to-image
This will load promotion block that being added when metadata exists after loadArea().
Note that loadArea() includes loadPostLCP which means **_this promotion block will be loaded after loadPostLCP()_**.
If you see refresh and go page bottom quickly you will find the promotion block get loaded slowly after everything else.
@Blainegunn  I don't know the background context why we want to load this after everything else, but this will do what is being asked.

Improved handling promotion block from metadata (for FedPub)

---

acrobat/styles/styles.css

Removing overflow:hidden from the widget container in order to fix an issue with error toasts.  Do we know why this overflow:hidden was there in the first place?

DCXY-16330 remove overflow: hidden

---

acrobat/scripts/scripts.js

Reslove: [MWPW-128858](https://jira.corp.adobe.com/browse/MWPW-128858)
US test URL
before: https://stage--dc--adobecom.hlx.page/foo
after: https://contentroot-dc-shared--dc--adobecom.hlx.page/foo
Other locale test (Korean)
before: https://stage--dc--adobecom.hlx.page/kr/foo
after: https://contentroot-dc-shared--dc--adobecom.hlx.page/kr/foo
This PR will update contentRoot to `/dc-shared`. It needs a decent QA to make sure nothing gets broken.

Updating contentRoot to dc-shared: This will fix 404 and other issues.

---

helix-sitemap.yaml

Addresses:
- https://github.com/adobe/helix-admin/issues/1198
- [MWPW-129768](https://jira.corp.adobe.com/browse/MWPW-129768)
Related:
- https://www.hlx.live/developer/sitemap#specifying-multiple-hreflangs-for-one-subtree
- https://github.com/adobe/helix-shared/pull/802
- https://github.com/adobe/helix-admin/pull/1207
- https://hparra-multiple-hreflang--dc--adobecom.hlx.page/
Post-merge:
- Run `curl -vX POST https://admin.hlx.page/sitemap/adobecom/dc/main/dc-shared/assets/sitemap.xml`

Use new multiple hreflang feature

---

acrobat/styles/styles.css

Trying to resolve: [MWPW-129281](https://jira.corp.adobe.com/browse/MWPW-129281)
Before: https://stage--dc--adobecom.hlx.page/acrobat/online/sign-pdf
After: https://cls-improve--dc--adobecom.hlx.page/acrobat/online/sign-pdf
QA note: I recommend to test with 3G speed. You should be able to see the layout shift difference.

Helping the CLS issue.

---

helix-sitemap.yaml

Fix targeting for Hebrew and Thai so they only match Israel and Thailand (like dexter), fix misconfigured English and Hindi for India, consolidate Russian Russian and Simplified Chinese.
See validation at https://git.corp.adobe.com/rea50414/notebooks/blob/main/milo-sitemap-hrelang-yaml.ipynb 
Addresses: 
- https://jira.corp.adobe.com/browse/MWPW-129768
- https://jira.corp.adobe.com/browse/MWPW-129652
- https://jira.corp.adobe.com/browse/MWPW-130428
- https://hparra-fix-sitemaps-again--dc--adobecom.hlx.page/
Post-merge:
- Run `curl -vX POST https://admin.hlx.page/sitemap/adobecom/dc/main/dc-shared/assets/sitemap.xml`

Fix hreflangs for Hebrew, Thai, Hindi, English (India), Russian (Russia) and Simplified Chinese

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js

There are articles on Internet about innerText vs textContent. In addition, JSDOM doesn't support innerText (https://github.com/jsdom/jsdom/issues/1245).

textContent is better

---

acrobat/scripts/scripts.js

Lang attribute in the bg and ee regional pages is 'en'.
**Resolves:** https://jira.corp.adobe.com/browse/MWPW-132555
**Links:**
Before: 
https://www.stage.adobe.com/bg/acrobat/online/jpg-to-pdf.html
https://www.stage.adobe.com/ee/acrobat/online/jpg-to-pdf.html
After: 
https://mwpw_132555-lang-attribute-for-bg-and-ee--dc--adobecom.hlx.page/bg/acrobat/online/jpg-to-pdf
https://mwpw_132555-lang-attribute-for-bg-and-ee--dc--adobecom.hlx.page/ee/acrobat/online/jpg-to-pdf

MWPW-132555 - lang attribute for bg and ee locales

---

acrobat/scripts/scripts.js

Resolves: [MWPW-133115](https://jira.corp.adobe.com/browse/MWPW-133115)
`es-LA` means "spanish-Laos". `419` is the UN M49 code for "Latinoamerica".
- Before: https://www.adobe.com/la/acrobat/online/word-to-pdf.html
- After: https://hparra-patch-3--dc--adobecom.hlx.page/la/acrobat/online/word-to-pdf

Update itef for /la geo

---

acrobat/scripts/frictionless.js

Resolves: [MWPW-133578](https://jira.corp.adobe.com/browse/MWPW-133578)
Before: https://stage--dc--adobecom.hlx.page/acrobat/online/pdf-to-word
After: https://mwpw-133578-analytics-event-firing-unexpectidly--dc--adobecom.hlx.page/acrobat/online/pdf-to-word

MWPW-133578:Removed modalExist analytics event from modal:open

---

acrobat/blocks/eventwrapper/eventwrapper.css
acrobat/blocks/eventwrapper/eventwrapper.js

Resolves : [MWPW-129281](https://jira.corp.adobe.com/browse/MWPW-129281)

MWPW-129281 - CLS Regression

---

acrobat/styles/styles.css

*Added padding to how-to block to fix overlapping on tablet devices + added additional padding for desktop devices to match previous design
Resolves: [MWPW-134277](https://jira.corp.adobe.com/browse/MWPW-134277)
Test URLs:
Before: https://stage--dc--adobecom.hlx.page/acrobat/online/word-to-pdf
After: https://mwpw-134277-fix-overlap--dc--adobecom.hlx.page/acrobat/online/word-to-pdf

Added padding for how-to block

---

acrobat/scripts/scripts.js

dc-hosted/generate cache will always be the second half of the widget version tuple

replace hard-coded version with variable

---

.github/workflows/test-milo.yml

Try out workflow dispatch from Milo. The jobs is the same as run-inside.yml. Once the workflow dispatch works, some E2E tests will be moved to GitHub Actions.

MWPW-134543 Set up workflow for testing milo changes

---

acrobat/scripts/contentSecurityPolicy/prod.js

to support frictionless fill & sign.  worker-src:blob is usually sufficient for them to create their wasm proxies, but for old Safari we determined that child-src is also needed

DCXY-18423 add child-src:blob on prod for adobe proxy F&S support on old Safari <15.4

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js

Test proxy urls on stage only. This will fetch DC widget assets from the same www.adobe.com host as the rest of the page and should eliminate delay.

MWPW-127299 use stage proxy dc urls

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js
acrobat/scripts/scripts.js

use meta for versions consistently both for prefetch and in the block
and use the proxy url for dc-generate-cache on prod
DO NOT deploy to prod until prod hostname proxies have been deployed (WPS-23181 - morning of 8/17)

MWPW-127299 use proxy dc-generate-cache urls for prod

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js
acrobat/scripts/dcLana.js
acrobat/scripts/scripts.js

Resolves : MWPW-135230
LANA Logs for DC Widget were being skipped due to the fast tracking; fixed as well.
https://mwpw-135230--dc--adobecom.hlx.page/acrobat/online/john-test-verb?lanaDebug
https://mwpw-135230--dc--adobecom.hlx.page/documentcloud/merge-pdf-nopersonal?lanaDebug

MWPW-135230 DC Widget Backup / Logging Improvements 

---

acrobat/scripts/scripts.js

@auniverseaway kindly let us in on the secret that loadArea no longer hides our page.  Now we no longer need to prefetch utils.js to get loadArea done sooner.  This will not fix our waterfall, but it will push utils.js out later until most of our critical code is done.
This reverts commit c83a409bc9e1a450c4e03c06933dd351a181a181,
See #333

MWPW-135275 Revert "Merge pull request #333 from adobecom/loadareatest4"

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js

Revert "update to put widget on stage in new folder"

---

acrobat/blocks/eventwrapper/eventwrapper.js

Resolves: https://jira.corp.adobe.com/browse/MWPW-135029
Fix for exception _ReferenceError: chrome is not defined_ when running automated tests in Playwight's headless mode

MWPW-135029 - fixed exception 'chrome is not defined'

---

acrobat/scripts/contentSecurityPolicy/prod.js

We've been seeing CSP violations due to Franklin RUM requests being blocked. This commit allow-lists rum.hlx.page which is our RUM collection endpoint

fix(csp): enable RUM reporting

---

test/blocks/dc-converter-widget/dc-converter-widget.test.js
test/blocks/eventwrapper/mocks/body.html

- Eventwrapper needs #adobe_dc_sdk_launcher
- Dc-converter-widget has exceptions in loaded dc web scripts. Skiping verification for now, and will find a solution later.

Fix unit tests

---

test/e2e/frictionless/features/regression/caas.feature
test/e2e/frictionless/features/regression/eventwrapper.feature
test/e2e/frictionless/page-objects/caas.page.js
test/e2e/frictionless/page-objects/frictionless.page.js
test/e2e/frictionless/page-objects/passwordprotectpdf.page.js
test/e2e/frictionless/step-definitions/dc.steps.js

Resolves: [MWPW-132352](https://jira.corp.adobe.com/browse/MWPW-132352)

MWPW-132352: Added caas e2e tests

---

acrobat/img/favicons/favicon.webmanifest

Resolves: [MWPW-137403](https://jira.corp.adobe.com/browse/MWPW-137403)
Before: https://stage--dc--adobecom.hlx.live/acrobat/online/pdf-to-ppt
After: https://mwpw-137403-favicon-404--dc--adobecom.hlx.live/acrobat/online/pdf-to-ppt

MWPW-137403: Changed favicon icons path

---

.github/scripts/check_404.spec.js
.github/scripts/notify_slack.js
.github/scripts/query_index.js
.github/scripts/query_metadata.js
.github/workflows/metadata-published.yml
.github/workflows/page-published.yml
.github/workflows/test-page-published.yml

- The scripts are tested partially and locally. The integration of workflows can only be done after this PR is merged to the main branch. Some fixes and tuning may be needed then.
- Metadata and page changes are handled differently in this solution.
**Metadata Change**
When a resource is published in SharePoint, the helix-bot will create a workflow dispatch to the repo. The workflow `metadata-published.yml` compares the current to the previous metadata, and triggers the tests. 
The repo to be notified is configured in `admin.events.github.target` (see https://www.hlx.live/docs/configuration). If this value is not set, the repo configured in the AEM Sidekick is used.
**Page Change**
In order to have an insight on what pages are added, modified, and removed, we monitor the query index. …

MWPW-135236 Auto trigger test after SharePoint changes

---

acrobat/scripts/scripts.js

Resolves: [MWPW-136950](https://jira.corp.adobe.com/browse/MWPW-136950)
Before: https://stage--dc--adobecom.hlx.live/drafts/ratko/convert-pdf
After: https://mwpw-136950-preload-warnings--dc--adobecom.hlx.live/drafts/ratko/convert-pdf

MWPW-136950: Fixed css preload warnings

---

acrobat/scripts/scripts.js

Resolves: [MWPW-136950](https://jira.corp.adobe.com/browse/MWPW-136950)
Before: https://stage--dc--adobecom.hlx.live/drafts/ratko/convert-pdf
After: https://mwpw-136950-preload-warnings--dc--adobecom.hlx.live/drafts/ratko/convert-pdf

MWPW-136950: Removed crossorigin from link tag

---

tools/sidekick/config.json

* Add links to CaaS and FaaS configurator to the sidekick
* Link to these configurators has been added under Tools
* Configurator page will open in a new tab in browser
Resolves: [MWPW-134192](https://jira.corp.adobe.com/browse/MWPW-134192)
**Test URLs:**
- Before: https://main--dc--adobecom.hlx.page/?martech=off
- After: https://sidekick--dc--adobecom.hlx.page/?martech=off

Add caas and faas configurator to sidekick

---

acrobat/scripts/scripts.js

https://github.com/adobecom/milo/blob/main/libs/utils/utils.js#L301
I overlooked this line, pathname for sign.ing is `/` and canonical url pathname is `/acrobat/online/sign-pdf`, so adding `useDotHtml: true` doesn't work.
Resolves: [MWPW-138331](https://jira.corp.adobe.com/browse/MWPW-138331)
Before: https://stage--dc--adobecom.hlx.live/acrobat/online/sign-pdf
After: https://mwpw-138331-canonical-url-ing-pages--dc--adobecom.hlx.live/acrobat/online/sign-pdf

MWPW-138331: Fixed canonical url bug

---

acrobat/blocks/eventwrapper/eventwrapper.js

Resolves:
https://jira.corp.adobe.com/browse/MWPW-139266
**LINKS:**
Before:
- https://stage--dc--adobecom.hlx.live/acrobat/online/excel-to-pdf
- https://stage--dc--adobecom.hlx.live/acrobat/online/rotate-pdf
After:
- https://mwpw-139266-new-browser-ext-toast-feature-key--dc--adobecom.hlx.live/acrobat/online/excel-to-pdf
- https://mwpw-139266-new-browser-ext-toast-feature-key--dc--adobecom.hlx.live/acrobat/online/rotate-pdf
**NOTE:**
If the feature key **window.dc_hosted.disableChromeExtensionBanner** is set to true, browser extension toast will pop up; otherwise, the the regular browser extension modal will appear.
The feature key has not been implemented yet on the widget side. The expected date is around December 7th. Before its implementation, all verbs should work as before. Once the …

MWPW-139266 - Added feature key window.dc_hosted.disableExtensionBanner

---

acrobat/scripts/contentSecurityPolicy/prod.js

https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=DEX&title=Impact+on+Direct+file+Upload+and+Downloads+for+ACP+Users

MWPW-140457 add *.adobe.io to frame-src for downloads

---

acrobat/scripts/contentSecurityPolicy/dev.js
acrobat/scripts/contentSecurityPolicy/prod.js
acrobat/scripts/contentSecurityPolicy/stage.js

- Content policies added to dev, stage & prod
1. Open a [milo form](https://mwpw-139699--dc--adobecom.hlx.page/drafts/rivero/faas-milo).
2. Verify that the form's styling is now consistent with the production version: [Production Form](https://www.adobe.com/creativecloud/business/teams/request-information.html).
3. Confirm that the privacy strings have been removed
Resolves: [MWPW-139059](https://jira.corp.adobe.com/browse/MWPW-139059)
Test URLs:
Before: https://main--dc--adobecom.hlx.page/drafts/rivero/faas-milo
After: https://mwpw-139699--dc--adobecom.hlx.page/drafts/rivero/faas-milo

MWPW-139059 Issue with styling and privacy string

---

acrobat/blocks/dc-converter-widget-ootb/dc-converter-widget-ootb.css
acrobat/blocks/dc-converter-widget/dc-converter-widget.css
acrobat/blocks/eventwrapper/eventwrapper.css
acrobat/blocks/personalization/personalization.css
acrobat/styles/styles.css

Addressed the CLS (Cumulative Layout Shift) issue related to the widget moving from 70px to 30px briefly when a user tries to upload a file immediately after clicking the main CTA.
Reviews is not longer visible during file processing, preventing CLS spikes.
Throttle your Chrome to slow 3G or fast 3G.
Visit one of the "problem" pages, e.g., https://www.adobe.com/acrobat/online/compress-pdf.html.
Wait for the main CTA to become enabled (no longer grey).
Click on the CTA and try to upload a file.
Verify that the widget no longer moving, reviews disappears meanwhile file is processed  and that there is no significant CLS spike.
Resolves: [MWPW-140549](https://jira.corp.adobe.com/browse/MWPW-140549)
PDF to Word    
Before: https://www.adobe.com/acrobat/online/pdf-to-word.html
After: …

MWPW-140549: CLS on drag and drop or quick file selection

---

acrobat/scripts/scripts.js

Resolves: [MWPW-139879](https://jira.corp.adobe.com/browse/MWPW-139879)
Before: https://mwpw-139879-fix-lcp--dc--adobecom.hlx.live/acrobat/online/pdf-to-word
After: https://stage--dc--adobecom.hlx.live/acrobat/online/pdf-to-word

MWPW-139879: Fixed widget cache preloading issue

---

acrobat/scripts/scripts.js

Add pdf embed api support for DC pages to view the pdf on page
Resolves: [MWPW-141071](https://jira.corp.adobe.com/browse/MWPW-141071)
Test URLs:
Before: https://main--dc--adobecom.hlx.live/drafts/rivero/adobe-acrobat-microsoft-365-brief?martech=off
After: [https://mwpw-141071--dc--adobecom.hlx.live?martech=off](https://mwpw-141071--dc--adobecom.hlx.live/?martech=off)

MWPW-141071 : Prod API Client ID - Update to support PDFs displayed in SDK viewer

---

acrobat/styles/styles.css

Resolves: [MWPW-141293](https://jira.corp.adobe.com/browse/MWPW-141293)
This code is moved and merged into https://git.corp.adobe.com/dc/dc-pdfverbs-web/pull/4142
Test URLs:
Before: https://main--dc--adobecom.hlx.live/acrobat/online/pdf-editor?martech=off
After: https://mwpw-141293--dc--adobecom.hlx.live/acrobat/online/pdf-editor?martech=off&app!versions=latest

MWPW-141293 - Regression: transparent area in widget completion stage is now white

---

acrobat/scripts/fallback.js
head.html
test/scripts/fallback.test.js

MWPW-141685: Adds a browser fallback mechanism to redirect users on unsupported browser paths.
This update is ensuring that visitors on unsupported browsers are guided to the right information or support pages.
**Highlights:**
- **Dynamic Redirection:** Automatically redirects users to a specific Adobe Acrobat end-of-life page or a general Adobe support page, depending on their accessed URL.
- **Pattern Matching:** Employs regular expressions to match and handle different URL paths for redirection.
Resolves: [MWPW-141685](https://jira.corp.adobe.com/browse/MWPW-141685)
Test URLs:
Before: https://main--dc--adobecom.hlx.live/acrobat/resources/benefits-of-digital-notes-for-students?martech=off
After: https://mwpw-141685--dc--adobecom.hlx.live/acrobat/resources/benefits-of-digital-notes-for-st …

MWPW-141685 - Fallback Redirection for Unsupported URLs

---

edgeworkers/Acrobat_DC_web_prod/bundle.json

- The workflow will use prod.js and stage.js from `acrobat/scripts/contentSecurityPolicy/`
- The bundle version is for Acrobat_DC_web_stage. Still finding a solution for managing both prod and stage bundle versions.

Test EdgeWorker deployment on Acom stage

---

test/e2e/features/regression/converter.feature
test/e2e/features/regression/eventwrapper.feature
test/e2e/step-definitions/dc.steps.js

- Sign PDF is changed to L1. Remove Sign PDF test cases and add it to L1.
- Pricing checking step may take longer than 1 min
- Test cases MWPW-137251 and MWPW-137439 are set inactive in Jira.

Fix E2E tests

---

edgeworkers/Acrobat_DC_web_prod/utils/locales.js

For en-in, were using en-gb, then running the widget with en-us, resulting in a flicker with two different strings for the header.

MWPW-146016 English (India) should use en-us gen cache fallback to match widget

---

acrobat/scripts/scripts.js

Resolves: [MWPW-147215](https://jira.corp.adobe.com/browse/MWPW-147215)
Enables PDF SDK viewer base on the env we want it to test using a query string to set the proper env to test via query string
env=page for test main under hlx.page
env=stagePage for test stage under hlx.page
After merge we should be able to test it:
- https://main--dc--adobecom.hlx.page/acrobat/business/reports/sdk/adobe-acrobat-microsoft-365-brief?env=page
- https://stage--dc--adobecom.hlx.page/acrobat/business/reports/sdk/adobe-acrobat-microsoft-365-brief?env=stagePage
- https://mwpw-147215--dc--adobecom.hlx.page/

MWPW-147215: PDF inline SDK viewer envs

---

package-lock.json
package.json

The vulnerable [semver](https://www.npmjs.com/package/semver) version was used by Cucumber. The latest Cucumber resolves the issue.
Test URLs:
N/A

MWPW-147992 Upgrade the semver package version

---

acrobat/blocks/interactive-marquee/interactive-marquee.js

Resolves: [MWPW-149225](https://jira.corp.adobe.com/browse/MWPW-149225)
Adds specific attributes to track clicks under marquee navigation when user switch between videos
`daa-lh="marquee-nav"` and `daa-lh="btn-{1,2,3}"`
Test url: 
Before: https://main--dc--adobecom.hlx.page/drafts/rivero/MWPW-148327/interactive-marquee
After: https://mwpw-149225--dc--adobecom.hlx.page/drafts/rivero/MWPW-148327/interactive-marquee

MWPW-149225: DC Interactive Marquee Tracking attributes for analytics

---

.github/workflows/fg-sync-repos.yml

Checkout Action v2 seems to be working for milo, bacom and cc. But fails on dc for some reason.
Upgrading to v3 and testing with a temp dc clone repo seems to have worked.

MWPW-146848: Repo Sync checkout action version update

---

acrobat/scripts/scripts.js

**Description**
This PR adds the `stageDomainsMap` to the config allowing links to be environment-aware.
More about this new feature can be found in [here](https://github.com/orgs/adobecom/discussions/2437).
Resolves: [MWPW-151457](https://jira.corp.adobe.com/browse/MWPW-151457)

[MWPW 151457] Added stage domains map to make links environment-aware

---

acrobat/scripts/scripts.js

Put eager loading on the image in a `marquee` and `marquee small`.
Resolves: [MWPW-153563](https://jira.corp.adobe.com/browse/MWPW-153563)
**Test URLs**
Before:
https://main--dc--adobecom.hlx.live/acrobat/how-to/pdf-editor-pdf-files  (marquee)
https://main--dc--adobecom.hlx.live/acrobat/business/resources  (marquee small)
https://main--dc--adobecom.hlx.live/acrobat/online/word-to-pdf  (no marquee)
After:
https://mwpw-153563--dc--adobecom.hlx.live/acrobat/how-to/pdf-editor-pdf-files  (marquee)
https://mwpw-153563--dc--adobecom.hlx.live/acrobat/business/resources (marquee small)
https://mwpw-153563--dc--adobecom.hlx.live/acrobat/online/word-to-pdf  (no marquee)

MWPW-153563 Make loadLCPImage smarter

---

acrobat/scripts/scripts.js

Resolves: [MWPW-155429](https://jira.corp.adobe.com/browse/MWPW-155429)
Test URL: https://mwpw-155429--dc--adobecom.hlx.page/

MWPW-155429: Removed www.adobe.com from stagedomains map

---

acrobat/scripts/scripts.js

Replaces #741
Give IMS a chance to start loading sooner. IMS:Ready event was firing much later than necessary.
Test url:
https://imssoonest--dc--adobecom.hlx.page/

kick off async loading of IMS before awaiting loadArea

---

acrobat/blocks/acom-widget/acom-widget.js

resolves: [MWPW-157717](https://jira.corp.adobe.com/browse/MWPW-157717)

sending analytics for scenario where multiple files are selected

---

acrobat/styles/styles.css

MWPW-157941

---

acrobat/blocks/verb-widget/verb-widget.js

Resolves : [MWPW-156372](https://jira.corp.adobe.com/browse/MWPW-156372)

MWPW-156372

---

acrobat/blocks/nonprofit/nonprofit.css

Resolves: [MWPW-157037](https://jira.corp.adobe.com/browse/MWPW-157037)

MWPW-157037: Removed hidden overflow for logo

---

acrobat/blocks/verb-widget/verb-widget.js

MWPW-159098 - Race Condition ?  

---

acrobat/blocks/prompt-card/prompt-card.css
acrobat/blocks/prompt-card/prompt-card.js
test/scripts/scripts-preloads.test.js

Resolves: [MWPW-157780](https://jira.corp.adobe.com/browse/MWPW-157780)

MWPW-157780 Update based on design audit

---

acrobat/blocks/verb-widget/verb-widget.js

Revert "MWPW-160726"

---

acrobat/scripts/scripts.js

- The old code only checks `marquee` block. Some pages may use `hero-marquee`. 
- The image in a hero marquee should have the loading eager attribute.
Resolves: [MWPW-160879](https://jira.corp.adobe.com/browse/MWPW-160879)
**Test URLs**
Before : http://main--dc--adobecom.hlx.live/acrobat/features/modify-pdfs
After : http://MWPW-160879--dc--adobecom.hlx.live/acrobat/features/modify-pdfs

MWPW-160879 Add hero-marquee in loadLCPImage

---

acrobat/blocks/verb-widget/verb-widget.js

Reload the page if user is traversing the history.
Resolves: [MWPW-161195](https://jira.corp.adobe.com/browse/MWPW-161195)

MWPW-161195 Reload page if going backward

---

acrobat/blocks/dc-converter-widget/dc-converter-widget.js
test/blocks/dc-converter-widget/dc-converter-widget.jest.js

Resolves: [MWPW-163902](https://jira.corp.adobe.com/browse/MWPW-163902)

MWPW-163902 Fix edge snippet fallback

---

acrobat/blocks/rnr/rnr.js
test/blocks/rnr/rnr.test.js

The `snapshot` was badly implemented, because the `localStorage` entry was common between all frictionless pages. This modifies the `rnr-snapshot` stored in `localStorage` to contain data per given verb.
Resolves: [MWPW-167827](https://jira.corp.adobe.com/browse/MWPW-167827)
Current: https://main--dc--adobecom.hlx.page/acrobat/online/word-to-pdf
Test URLs: 
- https://mwpw-167827--dc--adobecom.hlx.page/acrobat/online/word-to-pdf
- https://mwpw-167827--dc--adobecom.hlx.page/acrobat/online/jpg-to-pdf

MWPW-167827: RNR snapshot fix

---

acrobat/styles/styles.css

Pre-Unity verb CLS is on the rise. This [change](https://github.com/adobecom/dc/commit/4ec21c2c4e64e0491b861a5c5f419feb7c7edc31
) was made around the same time (ty @TsayAdobe) 
We're going to put it back 
Resolves: [MWPW-17016](https://jira.corp.adobe.com/browse/MWPW-17016)
- http://mwpw-17016--dc--adobecom.aem.page/acrobat/online/compress-pdf

MWPW-17016

---

acrobat/blocks/verb-widget/verb-widget.js

We are already sending the browser tab closure events to AA. Let's also send them t our new splunk analytics.
Resolves: [MWPW-170827](https://jira.corp.adobe.com/browse/MWPW-170827)

[MWPW-170827] send browser tab closure event to splunk

---

acrobat/blocks/verb-widget/verb-widget.js

Introduce a reliable LCP-based analytics loader for browsers without support for LCP observer with fallback and logs to lana. 
Resolves: [MWPW-171714](https://jira.corp.adobe.com/browse/MWPW-171714)
- http://main--dc--adobecom.hlx.page/acrobat/online/compress-pdf
- http://mwpw-171714--dc--adobecom.hlx.page/acrobat/online/compress-pdf

MWPW-171714: Fix Analytics Fail to Load on Safari

---

acrobat/blocks/verb-widget/verb-widget.css
acrobat/blocks/verb-widget/verb-widget.js

Moved Verb Widget tool tip to pop from the top! 
It's also pushed to the center of the widget a bit more to avoid being cut off.
Resolves: [MWPW-170318](https://jira.corp.adobe.com/browse/MWPW-170318)
- http://mwpw-170318--dc--adobecom.aem.page/acrobat/online/compress-pdf

MWPW-170318 Verb Widget Tool-Tip Fix

---

.github/workflows/deploy-edgeworker.yml
edgeworkers/Acrobat_DC_web_prod/edgekv.js
edgeworkers/Acrobat_DC_web_prod/edgekv_tokens.js
edgeworkers/Acrobat_DC_web_prod/main.js
edgeworkers/scripts/setbundle.js

- Include the required `edgekv.js` file from Akamai
- EdgeKV access token reference is stored as a GitHub Actions secret. 
- The GitHub Action [`jdmevo123/akamai-edgeworker-action`](https://github.com/jdmevo123/akamai-edgeworker-action) for deploying EdgeWorkers doesn't work with EdgeKV. It has been improved and hosted at [`adobecom/akamai-edgeworker-action`](https://github.com/adobecom/akamai-edgeworker-action). 
Resolves: [MWPW-170393](https://jira.corp.adobe.com/browse/MWPW-170393)
N/A

MWPW-170393 Read EdgeKV and Inject the prerendered snippet

---

acrobat/blocks/verb-widget/verb-widget.js

- Remove the prerender element if it exists when the verb widget is displayed.
Resolves: [MWPW-170394](https://jira.corp.adobe.com/browse/MWPW-170394)
- http://mwpw-170394x--dc--adobecom.aem.page/acrobat/online/compress-pdf

MWPW-170394 Handle prerender element

---

acrobat/blocks/rnr/rnr.js

Only pages on production hosts can access the RNR production endpoint.
Resolves: [MWPW-171598](https://jira.corp.adobe.com/browse/MWPW-171598)
- http://main--dc--adobecom.aem.page/acrobat/online/sign-pdf
- http://mwpw-171598--dc--adobecom.aem.page/acrobat/online/sign-pdf

MWPW-171598 Update the list of prod hosts for RNR

---

acrobat/blocks/verb-widget/verb-widget.js
acrobat/scripts/alloy/verb-widget.js

Tab closure event is being handled in code and event is being sent to Adobe Analytics but not to splunk. Send beacon event instead of fetch for tab closure analytics. sendBeacon is async, unlike fetch and hence should be able to send data to analytics during tab close.
Resolves: [MWPW-171660](https://jira.corp.adobe.com/browse/MWPW-171660)
- hhttps://stage--dc--adobecom.hlx.page/acrobat/online/test/pdf-to-word
- https://stage--dc--adobecom.hlx.page/acrobat/online/test/pdf-to-word?unitylibs=tab-closure-beacon

[MWPW-171660] Tab closure event is not logged in splunk

---

acrobat/blocks/verb-widget/verb-widget.js
acrobat/scripts/alloy/verb-widget.js

remove the "beforeunload" listener once we have handled it after tab close. Also added handleExit for events before uploading
Resolves: [MWPW-172923](https://jira.corp.adobe.com/browse/MWPW-172923)
- https://rosahu-mwpw-172923--dc--adobecom.aem.page/acrobat/online/compress-pdf

[MWPW-172923] Multiple browser tab closure events are being sent for single upload instance

---

acrobat/blocks/verb-widget/verb-widget.css

Fix the position and size 
Resolves: [MWPW-172124](https://jira.corp.adobe.com/browse/MWPW-172124)
http://main--dc--adobecom.aem.page/acrobat/online/compress-pdf
http://main--dc--adobecom.aem.page/acrobat/online/sign-pdf
http://main--dc--adobecom.aem.page/acrobat/online/add-pdf-page-numbers
http://mwpw-172124--dc--adobecom.aem.page/acrobat/online/compress-pdf
http://mwpw-172124--dc--adobecom.aem.page/acrobat/online/sign-pdf
http://mwpw-172124--dc--adobecom.aem.page/acrobat/online/add-pdf-page-numbers

MWPW-172124: Displaying the info icon on safari browsers

---

acrobat/blocks/verb-widget/verb-widget.js

chunk upload event was not being logged since event type has been changed from generic to warn chunk failure. Needed this update in slytherin error map as well
Injection PR: https://github.com/adobecom/unity/pull/389/files 

Chunk upload failure events are missing from splunk logging

---

acrobat/blocks/verb-widget/verb-widget.css

Widget wrapper min-width  to 1200 when bigger screens
Resolves: [MWPW-173558](https://jira.corp.adobe.com/browse/MWPW-173558)
- https://mwpw-173558--dc--adobecom.aem.live/acrobat/online/compress-pdf

MWPW-173558: Verb widget consonant dropzoone max width

---

acrobat/blocks/rnr/rnr.js

The attribute `aria-live` doesn't work as expected. Setting the focus and/or adding `aria-relevant` didn't help. Use `role` instead. 
Resolves: [MWPW-164769](https://jira.corp.adobe.com/browse/MWPW-164769)
- https://mwpw-164769--dc--adobecom.aem.live/acrobat/online/compress-pdf

MWPW-164769 Use role alert for thank you message

---

acrobat/blocks/verb-widget/verb-widget.css

Fix tool-tip placement on mobile widget
adde tool-tip css to verb-widget since we can't rely on `icons.css` loading anymore
Resolves: [MWPW-173774](https://jira.corp.adobe.com/browse/MWPW-173774)
- https://mwpw-173774--dc--adobecom.aem.live/acrobat/online/compress-pdf

MWPW-173774

---

acrobat/blocks/rnr/rnr.js

No autofocus on `textarea` after ⭐ rating selected 
Resolves: [MWPW-173777](https://jira.corp.adobe.com/browse/MWPW-173777)
- https://mwpw-173777--dc--adobecom.aem.live/acrobat/online/compress-pdf

MWPW-173777

---

acrobat/blocks/verb-widget/verb-widget.js

set exitFlag as true before redirect event being sent to unity. 
Due to the race condition, intermittently, if redirection begins before the exit flag has been set to true,  the "beforeunload" listener gets invoked. Since the exitFlag is not yet set to true, we see the browser closure confirmation dialogue.
Also, this could be non injection and on prod as well.
Resolves: [MWPW-173837](https://jira.corp.adobe.com/browse/MWPW-173837)
- https://mwpw-XXXXXX--dc--adobecom.aem.live/acrobat/online/compress-pdf

[MWPW-173837] intermittently "leave site" confirmation prompt display in splash screen

---

.github/workflows/run-lint.yml
.github/workflows/run-tests.yml
tools/cspUpdate/cspUpdate.js

Updates NodeJS version across the DC repository to address the end-of-life of NodeJS 18 (April 30, 2025).
- **GitHub Actions Workflows**: Updated to use NodeJS 22.x
- `.github/workflows/run-tests.yml`
- `.github/workflows/run-lint.yml`
- **CSP Update Tool**: Updated to require NodeJS 20 or newer
- `tools/cspUpdate/cspUpdate.js`
NodeJS 18 has reached end-of-life on April 30, 2025. This update ensures the repository continues to use supported NodeJS versions for both CI/CD workflows and development tools.
Fixes: MWPW-176062

MWPW-176062: Update NodeJS version from 18 to 20/22

---

acrobat/blocks/verb-widget/verb-widget.css
acrobat/blocks/verb-widget/verb-widget.js

Updates Widget subtext to a limits variable so it can be more easily maintained
Update solo upload cta with DOM tagging and override for style clash with `notifications.css`  
Resolves: [MWPW-177050](https://jira.corp.adobe.com/browse/MWPW-177050)
- https://mwpw-177050--dc--adobecom.aem.live/acrobat/online/compress-pdf

 MWPW-177050

---

acrobat/blocks/verb-widget/verb-widget.js

Aria Label for file upload buttons 
alt text for svg images, defaults to verb code name if empty 
Resolves: [MWPW-177354](https://jira.corp.adobe.com/browse/MWPW-177354)
- https://mwpw-177354--dc--adobecom.aem.live/acrobat/online/compress-pdf

MWPW-177354
